# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'HomePage.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QLineEdit, QMainWindow, QProgressBar,
    QPushButton, QRadioButton, QSizePolicy, QStackedWidget,
    QWidget)
import img_rc
import icon_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(1921, 987)
        MainWindow.setMinimumSize(QSize(1921, 987))
        MainWindow.setMaximumSize(QSize(1929, 987))
        icon = QIcon()
        icon.addFile(u":/envanter/images/img/iconPoyraz.png", QSize(), QIcon.Normal, QIcon.Off)
        icon.addFile(u":/envanter/images/img/iconPoyraz.png", QSize(), QIcon.Normal, QIcon.On)
        icon.addFile(u":/envanter/images/img/iconPoyraz.png", QSize(), QIcon.Disabled, QIcon.Off)
        icon.addFile(u":/envanter/images/img/iconPoyraz.png", QSize(), QIcon.Disabled, QIcon.On)
        icon.addFile(u":/envanter/images/img/iconPoyraz.png", QSize(), QIcon.Active, QIcon.Off)
        icon.addFile(u":/envanter/images/img/iconPoyraz.png", QSize(), QIcon.Active, QIcon.On)
        icon.addFile(u":/envanter/images/img/iconPoyraz.png", QSize(), QIcon.Selected, QIcon.Off)
        icon.addFile(u":/envanter/images/img/iconPoyraz.png", QSize(), QIcon.Selected, QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(Qt.LeftToRight)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(1929, 987))
        self.centralwidget.setMaximumSize(QSize(1929, 987))
        self.centralwidget.setStyleSheet(u"#centralwidget{\n"
"background-color: rgb(74, 16, 241);\n"
"}")
        self.leftMenu = QFrame(self.centralwidget)
        self.leftMenu.setObjectName(u"leftMenu")
        self.leftMenu.setGeometry(QRect(0, 0, 180, 981))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftMenu.sizePolicy().hasHeightForWidth())
        self.leftMenu.setSizePolicy(sizePolicy)
        self.leftMenu.setMinimumSize(QSize(85, 630))
        self.leftMenu.setMaximumSize(QSize(180, 99999))
        self.leftMenu.setStyleSheet(u"#leftMenu{\n"
"background-color: rgb(74, 16, 241);\n"
"}")
        self.leftMenu.setFrameShape(QFrame.StyledPanel)
        self.leftMenu.setFrameShadow(QFrame.Raised)
        self.logoWidget = QWidget(self.leftMenu)
        self.logoWidget.setObjectName(u"logoWidget")
        self.logoWidget.setGeometry(QRect(1, 20, 180, 124))
        sizePolicy.setHeightForWidth(self.logoWidget.sizePolicy().hasHeightForWidth())
        self.logoWidget.setSizePolicy(sizePolicy)
        self.logoWidget.setMinimumSize(QSize(128, 124))
        self.logoWidget.setMaximumSize(QSize(180, 124))
        self.logoWidget.setSizeIncrement(QSize(0, 100))
        self.logoWidget.setStyleSheet(u"")
        self.label_30 = QLabel(self.logoWidget)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(0, 99, 181, 3))
        self.label_30.setStyleSheet(u"background-color: rgb(32, 123, 255);")
        self.label_48 = QLabel(self.logoWidget)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(20, -24, 141, 141))
        self.label_48.setStyleSheet(u"border-image: url(:/envanter/images/img/zinkVTOL (2).png);")
        self.btn_homePage = QPushButton(self.leftMenu)
        self.btn_homePage.setObjectName(u"btn_homePage")
        self.btn_homePage.setGeometry(QRect(-50, 160, 250, 40))
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.btn_homePage.sizePolicy().hasHeightForWidth())
        self.btn_homePage.setSizePolicy(sizePolicy1)
        self.btn_homePage.setMinimumSize(QSize(70, 40))
        self.btn_homePage.setMaximumSize(QSize(250, 40))
        font = QFont()
        font.setFamilies([u"Favela-Medium"])
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.btn_homePage.setFont(font)
        self.btn_homePage.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-Medium\";")
        icon1 = QIcon()
        icon1.addFile(u":/icon/images/icon/anaSayfa.png", QSize(), QIcon.Normal, QIcon.Off)
        icon1.addFile(u":/icon/images/icon/anaSayfa.png", QSize(), QIcon.Normal, QIcon.On)
        icon1.addFile(u":/icon/images/icon/anaSayfa.png", QSize(), QIcon.Disabled, QIcon.Off)
        icon1.addFile(u":/icon/images/icon/anaSayfa.png", QSize(), QIcon.Active, QIcon.On)
        self.btn_homePage.setIcon(icon1)
        self.btn_homePage.setIconSize(QSize(50, 120))
        self.btn_homePage.setFlat(True)
        self.btn_package = QPushButton(self.leftMenu)
        self.btn_package.setObjectName(u"btn_package")
        self.btn_package.setGeometry(QRect(-38, 280, 231, 40))
        sizePolicy1.setHeightForWidth(self.btn_package.sizePolicy().hasHeightForWidth())
        self.btn_package.setSizePolicy(sizePolicy1)
        self.btn_package.setMinimumSize(QSize(70, 40))
        self.btn_package.setMaximumSize(QSize(250, 40))
        self.btn_package.setFont(font)
        self.btn_package.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-Medium\";")
        icon2 = QIcon()
        icon2.addFile(u":/icon/images/icon/um.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_package.setIcon(icon2)
        self.btn_package.setIconSize(QSize(50, 120))
        self.btn_package.setFlat(True)
        self.btn_mission = QPushButton(self.leftMenu)
        self.btn_mission.setObjectName(u"btn_mission")
        self.btn_mission.setGeometry(QRect(-51, 400, 250, 40))
        sizePolicy1.setHeightForWidth(self.btn_mission.sizePolicy().hasHeightForWidth())
        self.btn_mission.setSizePolicy(sizePolicy1)
        self.btn_mission.setMinimumSize(QSize(70, 40))
        self.btn_mission.setMaximumSize(QSize(250, 40))
        self.btn_mission.setFont(font)
        self.btn_mission.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-Medium\";")
        icon3 = QIcon()
        icon3.addFile(u":/icon/images/icon/Mission.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_mission.setIcon(icon3)
        self.btn_mission.setIconSize(QSize(50, 120))
        self.btn_mission.setFlat(True)
        self.btn_dataFlight = QPushButton(self.leftMenu)
        self.btn_dataFlight.setObjectName(u"btn_dataFlight")
        self.btn_dataFlight.setGeometry(QRect(-53, 520, 250, 40))
        sizePolicy1.setHeightForWidth(self.btn_dataFlight.sizePolicy().hasHeightForWidth())
        self.btn_dataFlight.setSizePolicy(sizePolicy1)
        self.btn_dataFlight.setMinimumSize(QSize(70, 40))
        self.btn_dataFlight.setMaximumSize(QSize(250, 40))
        self.btn_dataFlight.setFont(font)
        self.btn_dataFlight.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-Medium\";")
        icon4 = QIcon()
        icon4.addFile(u":/icon/images/icon/flightdata.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_dataFlight.setIcon(icon4)
        self.btn_dataFlight.setIconSize(QSize(50, 120))
        self.btn_dataFlight.setFlat(True)
        self.btn_preFlight = QPushButton(self.leftMenu)
        self.btn_preFlight.setObjectName(u"btn_preFlight")
        self.btn_preFlight.setGeometry(QRect(-50, 640, 250, 40))
        sizePolicy1.setHeightForWidth(self.btn_preFlight.sizePolicy().hasHeightForWidth())
        self.btn_preFlight.setSizePolicy(sizePolicy1)
        self.btn_preFlight.setMinimumSize(QSize(70, 40))
        self.btn_preFlight.setMaximumSize(QSize(250, 40))
        self.btn_preFlight.setFont(font)
        self.btn_preFlight.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-Medium\";")
        icon5 = QIcon()
        icon5.addFile(u":/icon/images/icon/preFlight.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_preFlight.setIcon(icon5)
        self.btn_preFlight.setIconSize(QSize(50, 120))
        self.btn_preFlight.setFlat(True)
        self.btn_settings = QPushButton(self.leftMenu)
        self.btn_settings.setObjectName(u"btn_settings")
        self.btn_settings.setGeometry(QRect(-50, 760, 250, 40))
        sizePolicy1.setHeightForWidth(self.btn_settings.sizePolicy().hasHeightForWidth())
        self.btn_settings.setSizePolicy(sizePolicy1)
        self.btn_settings.setMinimumSize(QSize(70, 40))
        self.btn_settings.setMaximumSize(QSize(250, 40))
        self.btn_settings.setFont(font)
        self.btn_settings.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-Medium\";")
        icon6 = QIcon()
        icon6.addFile(u":/icon/images/icon/stngs.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_settings.setIcon(icon6)
        self.btn_settings.setIconSize(QSize(50, 120))
        self.btn_settings.setFlat(True)
        self.label_29 = QLabel(self.leftMenu)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(0, 240, 181, 3))
        self.label_29.setStyleSheet(u"background-color: rgb(30, 7, 105);")
        self.label_31 = QLabel(self.leftMenu)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(0, 360, 181, 3))
        self.label_31.setStyleSheet(u"background-color: rgb(30, 7, 105);")
        self.label_36 = QLabel(self.leftMenu)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(0, 480, 181, 3))
        self.label_36.setStyleSheet(u"background-color: rgb(30, 7, 105);")
        self.label_41 = QLabel(self.leftMenu)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(0, 600, 181, 3))
        self.label_41.setStyleSheet(u"background-color: rgb(30, 7, 105);")
        self.label_44 = QLabel(self.leftMenu)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(0, 720, 181, 3))
        self.label_44.setStyleSheet(u"background-color: rgb(30, 7, 105);")
        self.label_46 = QLabel(self.leftMenu)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(0, 850, 181, 3))
        self.label_46.setStyleSheet(u"background-color: rgb(30, 7, 105);")
        self.btn_poyrazLogo = QPushButton(self.leftMenu)
        self.btn_poyrazLogo.setObjectName(u"btn_poyrazLogo")
        self.btn_poyrazLogo.setGeometry(QRect(25, 872, 131, 91))
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.btn_poyrazLogo.sizePolicy().hasHeightForWidth())
        self.btn_poyrazLogo.setSizePolicy(sizePolicy2)
        self.btn_poyrazLogo.setMinimumSize(QSize(75, 91))
        self.btn_poyrazLogo.setMaximumSize(QSize(156, 16777215))
        self.btn_poyrazLogo.setSizeIncrement(QSize(130, 0))
        icon7 = QIcon()
        icon7.addFile(u":/envanter/images/img/poyrazHavacilik.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_poyrazLogo.setIcon(icon7)
        self.btn_poyrazLogo.setIconSize(QSize(130, 120))
        self.btn_poyrazLogo.setFlat(True)
        self.anaFrame = QFrame(self.centralwidget)
        self.anaFrame.setObjectName(u"anaFrame")
        self.anaFrame.setGeometry(QRect(180, 0, 1741, 990))
        self.anaFrame.setMinimumSize(QSize(1180, 630))
        self.anaFrame.setMaximumSize(QSize(9999, 9999))
        self.anaFrame.setStyleSheet(u"")
        self.anaFrame.setFrameShape(QFrame.StyledPanel)
        self.anaFrame.setFrameShadow(QFrame.Raised)
        self.titleBar = QWidget(self.anaFrame)
        self.titleBar.setObjectName(u"titleBar")
        self.titleBar.setGeometry(QRect(-1, 1, 1831, 121))
        sizePolicy.setHeightForWidth(self.titleBar.sizePolicy().hasHeightForWidth())
        self.titleBar.setSizePolicy(sizePolicy)
        self.titleBar.setMinimumSize(QSize(0, 80))
        self.titleBar.setMaximumSize(QSize(16777215, 150))
        self.titleBar.setStyleSheet(u"#titleBar{\n"
"background-color: rgb(74, 16, 241);\n"
"}")
        self.labelTitle = QLabel(self.titleBar)
        self.labelTitle.setObjectName(u"labelTitle")
        self.labelTitle.setGeometry(QRect(40, 30, 1051, 61))
        font1 = QFont()
        font1.setFamilies([u"Favela-Bold"])
        font1.setPointSize(36)
        self.labelTitle.setFont(font1)
        self.labelTitle.setStyleSheet(u"background-color:rgba(74,16,241,255);\n"
"color: rgb(255, 255, 255);")
        self.labelTitle.setFrameShadow(QFrame.Plain)
        self.labelTitle.setLineWidth(0)
        self.label_7 = QLabel(self.titleBar)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 118, 1801, 20))
        self.label_7.setStyleSheet(u"background-color:rgb(32,123,255);")
        self.widget = QWidget(self.anaFrame)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(1, 120, 1791, 871))
        self.widget.setMinimumSize(QSize(1050, 530))
        self.widget.setMaximumSize(QSize(99999, 99999))
        self.stackedWidget = QStackedWidget(self.widget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(-1, -6, 1791, 931))
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QSize(0, 0))
        self.stackedWidget.setMaximumSize(QSize(9999999, 16777215))
        self.stackedWidget.setStyleSheet(u"#page_mission{\n"
"background-color:rgb(18,4,62);\n"
"}\n"
"#page_envanter{\n"
"background-color:rgb(18,4,62);\n"
"}\n"
"#page_package{\n"
"background-color:rgb(18,4,62);\n"
"}\n"
"#page_settings{\n"
"background-color:rgb(18,4,62);\n"
"}\n"
"#page_dataFlight{\n"
"background-color:rgb(18,4,62);\n"
"}\n"
"\n"
"")
        self.stackedWidget.setFrameShape(QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QFrame.Plain)
        self.page_envanter = QWidget()
        self.page_envanter.setObjectName(u"page_envanter")
        self.page_envanter.setStyleSheet(u"")
        self.rightWidget = QWidget(self.page_envanter)
        self.rightWidget.setObjectName(u"rightWidget")
        self.rightWidget.setGeometry(QRect(1350, 10, 391, 861))
        self.rightWidget.setMinimumSize(QSize(205, 0))
        self.rightWidget.setStyleSheet(u"#rightWidget{\n"
"background-color:rgba(255,255,255,0);\n"
"}")
        self.urunpic1 = QPushButton(self.rightWidget)
        self.urunpic1.setObjectName(u"urunpic1")
        self.urunpic1.setGeometry(QRect(120, 50, 180, 180))
        self.urunpic1.setMinimumSize(QSize(150, 100))
        self.urunpic1.setMaximumSize(QSize(200, 200))
        self.urunpic1.setStyleSheet(u"")
        self.urunpic1.setIconSize(QSize(20, 20))
        self.urunpic1.setFlat(True)
        self.urun1Sil = QPushButton(self.rightWidget)
        self.urun1Sil.setObjectName(u"urun1Sil")
        self.urun1Sil.setGeometry(QRect(60, 50, 40, 30))
        self.urun1Sil.setMaximumSize(QSize(40, 30))
        font2 = QFont()
        font2.setFamilies([u"Favela-SemiBold"])
        font2.setPointSize(10)
        self.urun1Sil.setFont(font2)
        self.urun1Sil.setStyleSheet(u"background-color:rgb(74,16,241);")
        self.urunpic2 = QPushButton(self.rightWidget)
        self.urunpic2.setObjectName(u"urunpic2")
        self.urunpic2.setGeometry(QRect(120, 250, 180, 180))
        self.urunpic2.setMinimumSize(QSize(150, 100))
        self.urunpic2.setMaximumSize(QSize(180, 180))
        self.urunpic2.setFlat(True)
        self.urun2Sil = QPushButton(self.rightWidget)
        self.urun2Sil.setObjectName(u"urun2Sil")
        self.urun2Sil.setGeometry(QRect(60, 250, 40, 30))
        self.urun2Sil.setMaximumSize(QSize(40, 30))
        self.urun2Sil.setFont(font2)
        self.urun2Sil.setStyleSheet(u"background-color:rgb(74,16,241);")
        self.urunpic3 = QPushButton(self.rightWidget)
        self.urunpic3.setObjectName(u"urunpic3")
        self.urunpic3.setGeometry(QRect(120, 450, 180, 180))
        self.urunpic3.setMinimumSize(QSize(150, 100))
        self.urunpic3.setMaximumSize(QSize(180, 180))
        self.urunpic3.setStyleSheet(u"")
        self.urunpic3.setFlat(True)
        self.urun3Sil = QPushButton(self.rightWidget)
        self.urun3Sil.setObjectName(u"urun3Sil")
        self.urun3Sil.setGeometry(QRect(60, 450, 40, 30))
        self.urun3Sil.setMaximumSize(QSize(40, 30))
        self.urun3Sil.setFont(font2)
        self.urun3Sil.setStyleSheet(u"background-color:rgb(74,16,241);")
        self.btn_sepeteEkle = QPushButton(self.rightWidget)
        self.btn_sepeteEkle.setObjectName(u"btn_sepeteEkle")
        self.btn_sepeteEkle.setGeometry(QRect(40, 680, 311, 101))
        self.btn_sepeteEkle.setMinimumSize(QSize(0, 80))
        font3 = QFont()
        font3.setFamilies([u"Favela-Medium"])
        font3.setPointSize(20)
        self.btn_sepeteEkle.setFont(font3)
        self.btn_sepeteEkle.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(32, 123, 255);\n"
"border-radius:10px;")
        self.urun2Sil.raise_()
        self.urun3Sil.raise_()
        self.btn_sepeteEkle.raise_()
        self.urunpic1.raise_()
        self.urunpic2.raise_()
        self.urunpic3.raise_()
        self.urun1Sil.raise_()
        self.btn_tansiyon = QPushButton(self.page_envanter)
        self.btn_tansiyon.setObjectName(u"btn_tansiyon")
        self.btn_tansiyon.setGeometry(QRect(50, 60, 210, 210))
        self.btn_tansiyon.setMinimumSize(QSize(150, 130))
        self.btn_tansiyon.setMaximumSize(QSize(210, 210))
        self.btn_tansiyon.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/tansiyon aleti1.png);")
        self.btn_telefon = QPushButton(self.page_envanter)
        self.btn_telefon.setObjectName(u"btn_telefon")
        self.btn_telefon.setGeometry(QRect(830, 320, 210, 210))
        self.btn_telefon.setMinimumSize(QSize(150, 130))
        self.btn_telefon.setMaximumSize(QSize(210, 210))
        self.btn_telefon.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/Cep Telefonu1.jpg.png);")
        self.btn_guckaynagi = QPushButton(self.page_envanter)
        self.btn_guckaynagi.setObjectName(u"btn_guckaynagi")
        self.btn_guckaynagi.setGeometry(QRect(310, 580, 210, 210))
        self.btn_guckaynagi.setMinimumSize(QSize(150, 130))
        self.btn_guckaynagi.setMaximumSize(QSize(210, 210))
        self.btn_guckaynagi.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/gucKaynagi1.png);")
        self.btn_tablet = QPushButton(self.page_envanter)
        self.btn_tablet.setObjectName(u"btn_tablet")
        self.btn_tablet.setGeometry(QRect(310, 320, 210, 210))
        self.btn_tablet.setMinimumSize(QSize(150, 130))
        self.btn_tablet.setMaximumSize(QSize(210, 210))
        self.btn_tablet.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/Tablet1.jpg.png);")
        self.btn_tablet.setFlat(True)
        self.btn_ilacKutusu = QPushButton(self.page_envanter)
        self.btn_ilacKutusu.setObjectName(u"btn_ilacKutusu")
        self.btn_ilacKutusu.setGeometry(QRect(310, 60, 210, 210))
        self.btn_ilacKutusu.setMinimumSize(QSize(150, 130))
        self.btn_ilacKutusu.setMaximumSize(QSize(210, 210))
        self.btn_ilacKutusu.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/ilacKutusu1.png);")
        self.btn_kulaklik = QPushButton(self.page_envanter)
        self.btn_kulaklik.setObjectName(u"btn_kulaklik")
        self.btn_kulaklik.setGeometry(QRect(50, 320, 210, 210))
        self.btn_kulaklik.setMinimumSize(QSize(150, 130))
        self.btn_kulaklik.setMaximumSize(QSize(210, 210))
        self.btn_kulaklik.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/Kulaklik1.jpg.png);")
        self.btn_nebulizator = QPushButton(self.page_envanter)
        self.btn_nebulizator.setObjectName(u"btn_nebulizator")
        self.btn_nebulizator.setGeometry(QRect(830, 60, 210, 210))
        self.btn_nebulizator.setMinimumSize(QSize(150, 130))
        self.btn_nebulizator.setMaximumSize(QSize(210, 210))
        self.btn_nebulizator.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/Nebulizator1.png);")
        self.btn_boyunluk = QPushButton(self.page_envanter)
        self.btn_boyunluk.setObjectName(u"btn_boyunluk")
        self.btn_boyunluk.setGeometry(QRect(50, 580, 210, 210))
        self.btn_boyunluk.setMinimumSize(QSize(150, 130))
        self.btn_boyunluk.setMaximumSize(QSize(210, 210))
        self.btn_boyunluk.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/Medikal boyunluk1.png);")
        self.btn_insulin = QPushButton(self.page_envanter)
        self.btn_insulin.setObjectName(u"btn_insulin")
        self.btn_insulin.setGeometry(QRect(570, 60, 210, 210))
        self.btn_insulin.setMinimumSize(QSize(150, 130))
        self.btn_insulin.setMaximumSize(QSize(210, 210))
        self.btn_insulin.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/\u0130nsulin kalemi1.png);")
        self.btn_kablo = QPushButton(self.page_envanter)
        self.btn_kablo.setObjectName(u"btn_kablo")
        self.btn_kablo.setGeometry(QRect(570, 580, 210, 210))
        self.btn_kablo.setMinimumSize(QSize(150, 130))
        self.btn_kablo.setMaximumSize(QSize(210, 210))
        self.btn_kablo.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/Kablo1.png);")
        self.btn_laptop = QPushButton(self.page_envanter)
        self.btn_laptop.setObjectName(u"btn_laptop")
        self.btn_laptop.setGeometry(QRect(570, 320, 210, 210))
        self.btn_laptop.setMinimumSize(QSize(150, 130))
        self.btn_laptop.setMaximumSize(QSize(210, 210))
        self.btn_laptop.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/laptop1.jpg.png);")
        self.stackedWidget.addWidget(self.page_envanter)
        self.page_package = QWidget()
        self.page_package.setObjectName(u"page_package")
        self.page_package.setStyleSheet(u"")
        self.leftFrame = QFrame(self.page_package)
        self.leftFrame.setObjectName(u"leftFrame")
        self.leftFrame.setGeometry(QRect(0, 0, 1741, 891))
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.leftFrame.sizePolicy().hasHeightForWidth())
        self.leftFrame.setSizePolicy(sizePolicy3)
        self.leftFrame.setMinimumSize(QSize(400, 50))
        self.leftFrame.setMaximumSize(QSize(16777215, 900))
        self.leftFrame.setFrameShape(QFrame.StyledPanel)
        self.leftFrame.setFrameShadow(QFrame.Raised)
        self.titleFrame = QFrame(self.leftFrame)
        self.titleFrame.setObjectName(u"titleFrame")
        self.titleFrame.setGeometry(QRect(26, 48, 811, 811))
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.titleFrame.sizePolicy().hasHeightForWidth())
        self.titleFrame.setSizePolicy(sizePolicy4)
        self.titleFrame.setMinimumSize(QSize(0, 0))
        self.titleFrame.setMaximumSize(QSize(999, 999))
        self.titleFrame.setInputMethodHints(Qt.ImhNone)
        self.titleFrame.setFrameShape(QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QFrame.Raised)
        self.widget_3 = QWidget(self.titleFrame)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(10, 40, 751, 231))
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMaximumSize(QSize(999, 999))
        self.widget_3.setStyleSheet(u"#QWidget{\n"
"background-color: rgb(32,123,255);\n"
"}")
        self.textisim = QLineEdit(self.widget_3)
        self.textisim.setObjectName(u"textisim")
        self.textisim.setGeometry(QRect(10, 30, 741, 31))
        font4 = QFont()
        font4.setFamilies([u"Favela-Medium"])
        font4.setPointSize(11)
        self.textisim.setFont(font4)
        self.textisim.setStyleSheet(u"background-color:rgb(255, 255, 255);\n"
"color:rgb(150,150,150);")
        self.textisim.setMaxLength(20)
        self.textSoyad = QLineEdit(self.widget_3)
        self.textSoyad.setObjectName(u"textSoyad")
        self.textSoyad.setGeometry(QRect(10, 70, 741, 31))
        self.textSoyad.setFont(font4)
        self.textSoyad.setStyleSheet(u"background-color: rgb(255,255,255);\n"
"color:rgb(150,150,150);")
        self.textSoyad.setMaxLength(20)
        self.textTelefon = QLineEdit(self.widget_3)
        self.textTelefon.setObjectName(u"textTelefon")
        self.textTelefon.setGeometry(QRect(10, 110, 741, 31))
        self.textTelefon.setFont(font4)
        self.textTelefon.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color:rgb(150,150,150);")
        self.textTelefon.setMaxLength(11)
        self.textTelefon.setFrame(True)
        self.textGondericiGemi = QLineEdit(self.widget_3)
        self.textGondericiGemi.setObjectName(u"textGondericiGemi")
        self.textGondericiGemi.setGeometry(QRect(10, 150, 741, 31))
        self.textGondericiGemi.setFont(font4)
        self.textGondericiGemi.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color:rgb(150,150,150);")
        self.textGondericiGemi.setMaxLength(20)
        self.textHedefGemi = QLineEdit(self.widget_3)
        self.textHedefGemi.setObjectName(u"textHedefGemi")
        self.textHedefGemi.setGeometry(QRect(10, 191, 741, 31))
        self.textHedefGemi.setFont(font4)
        self.textHedefGemi.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color:rgb(150,150,150);")
        self.textHedefGemi.setInputMethodHints(Qt.ImhNone)
        self.textHedefGemi.setMaxLength(20)
        self.textHedefGemi.setFrame(True)
        self.frame_4 = QFrame(self.titleFrame)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 0, 311, 51))
        self.frame_4.setMinimumSize(QSize(200, 41))
        self.frame_4.setMaximumSize(QSize(311, 80))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.labelPaketBilgisi = QLabel(self.frame_4)
        self.labelPaketBilgisi.setObjectName(u"labelPaketBilgisi")
        self.labelPaketBilgisi.setGeometry(QRect(35, 4, 281, 41))
        font5 = QFont()
        font5.setFamilies([u"Favela-Medium"])
        font5.setPointSize(20)
        font5.setBold(False)
        font5.setItalic(False)
        self.labelPaketBilgisi.setFont(font5)
        self.labelPaketBilgisi.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(18,4,62);")
        self.labelPaketBilgiBack = QLabel(self.frame_4)
        self.labelPaketBilgiBack.setObjectName(u"labelPaketBilgiBack")
        self.labelPaketBilgiBack.setGeometry(QRect(10, 10, 16, 31))
        self.labelPaketBilgiBack.setStyleSheet(u"background-color: rgb(32,123,255);")
        self.labelPaketBilgiBack.raise_()
        self.labelPaketBilgisi.raise_()
        self.labelPaketBilgisi_2 = QLabel(self.titleFrame)
        self.labelPaketBilgisi_2.setObjectName(u"labelPaketBilgisi_2")
        self.labelPaketBilgisi_2.setGeometry(QRect(46, 315, 291, 41))
        self.labelPaketBilgisi_2.setFont(font3)
        self.labelPaketBilgisi_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(18,4,62);")
        self.frame_15 = QFrame(self.titleFrame)
        self.frame_15.setObjectName(u"frame_15")
        self.frame_15.setGeometry(QRect(20, 360, 761, 441))
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setFrameShape(QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QFrame.Raised)
        self.paketurun2 = QPushButton(self.frame_15)
        self.paketurun2.setObjectName(u"paketurun2")
        self.paketurun2.setGeometry(QRect(0, 30, 220, 220))
        self.paketurun2.setMaximumSize(QSize(220, 220))
        self.paketurun2.setStyleSheet(u"QPushButton{\n"
"background-color:rgba(80, 70, 230,255);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.paketurun2.setFlat(False)
        self.paketurun1 = QPushButton(self.frame_15)
        self.paketurun1.setObjectName(u"paketurun1")
        self.paketurun1.setGeometry(QRect(260, 30, 220, 220))
        self.paketurun1.setMaximumSize(QSize(220, 220))
        self.paketurun1.setStyleSheet(u"QPushButton{\n"
"background-color:rgba(80, 70, 230,255);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.paketurun1.setFlat(False)
        self.paketurun3 = QPushButton(self.frame_15)
        self.paketurun3.setObjectName(u"paketurun3")
        self.paketurun3.setGeometry(QRect(520, 30, 220, 220))
        self.paketurun3.setMaximumSize(QSize(220, 220))
        self.paketurun3.setStyleSheet(u"QPushButton{\n"
"background-color:rgba(80, 70, 230,255);\n"
"border-radius:10px;\n"
"}")
        self.paketurun3.setFlat(False)
        self.btnOnayla = QPushButton(self.frame_15)
        self.btnOnayla.setObjectName(u"btnOnayla")
        self.btnOnayla.setGeometry(QRect(370, 300, 371, 51))
        self.btnOnayla.setFont(font3)
        self.btnOnayla.setStyleSheet(u"background-color: rgb(32, 123, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.btnOnayla.setAutoRepeatDelay(0)
        self.labelPaketBilgiBack_2 = QLabel(self.titleFrame)
        self.labelPaketBilgiBack_2.setObjectName(u"labelPaketBilgiBack_2")
        self.labelPaketBilgiBack_2.setGeometry(QRect(20, 320, 16, 31))
        self.labelPaketBilgiBack_2.setStyleSheet(u"background-color: rgb(32,123,255);")
        self.rightFrame = QFrame(self.page_package)
        self.rightFrame.setObjectName(u"rightFrame")
        self.rightFrame.setGeometry(QRect(850, 10, 900, 871))
        sizePolicy3.setHeightForWidth(self.rightFrame.sizePolicy().hasHeightForWidth())
        self.rightFrame.setSizePolicy(sizePolicy3)
        self.rightFrame.setMinimumSize(QSize(559, 521))
        self.rightFrame.setMaximumSize(QSize(900, 900))
        self.rightFrame.setStyleSheet(u"QWidget{\n"
"background-color: rgb(41, 9, 133);\n"
"}")
        self.rightFrame.setFrameShape(QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QFrame.Raised)
        self.frame = QFrame(self.rightFrame)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(20, 30, 881, 201))
        self.frame.setMinimumSize(QSize(552, 120))
        self.frame.setMaximumSize(QSize(999, 999))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.labelPaketBilgiBack_3 = QLabel(self.frame)
        self.labelPaketBilgiBack_3.setObjectName(u"labelPaketBilgiBack_3")
        self.labelPaketBilgiBack_3.setGeometry(QRect(20, 20, 16, 31))
        self.labelPaketBilgiBack_3.setStyleSheet(u"background-color: rgb(32,123,255);")
        self.labelPaketBilgisi_3 = QLabel(self.frame)
        self.labelPaketBilgisi_3.setObjectName(u"labelPaketBilgisi_3")
        self.labelPaketBilgisi_3.setGeometry(QRect(46, 15, 201, 41))
        self.labelPaketBilgisi_3.setFont(font3)
        self.labelPaketBilgisi_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(41,9,133);")
        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(23, 60, 131, 41))
        font6 = QFont()
        font6.setFamilies([u"Favela-Medium"])
        font6.setPointSize(14)
        font6.setBold(False)
        font6.setItalic(False)
        self.label_9.setFont(font6)
        self.label_9.setStyleSheet(u"background-color:rgb(41,9,133);\n"
"color:rgb(32,123,255);")
        self.label_9.setTextFormat(Qt.PlainText)
        self.pushButton_13 = QPushButton(self.frame)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(401, 105, 51, 28))
        icon8 = QIcon()
        icon8.addFile(u":/icon/images/icon/Katman 11.png", QSize(), QIcon.Normal, QIcon.Off)
        icon8.addFile(u":/icon/images/icon/Katman 11.png", QSize(), QIcon.Normal, QIcon.On)
        self.pushButton_13.setIcon(icon8)
        self.pushButton_13.setIconSize(QSize(40, 40))
        self.pushButton_13.setFlat(True)
        self.textNereden_lat = QLineEdit(self.frame)
        self.textNereden_lat.setObjectName(u"textNereden_lat")
        self.textNereden_lat.setGeometry(QRect(23, 100, 180, 40))
        font7 = QFont()
        font7.setPointSize(14)
        self.textNereden_lat.setFont(font7)
        self.textNereden_lat.setStyleSheet(u"background-color:rgb(255, 255, 255);")
        self.textNereye_lat = QLineEdit(self.frame)
        self.textNereye_lat.setObjectName(u"textNereye_lat")
        self.textNereye_lat.setGeometry(QRect(465, 100, 180, 40))
        self.textNereye_lat.setFont(font7)
        self.textNereye_lat.setStyleSheet(u"background-color:rgb(255, 255, 255);")
        self.label_10 = QLabel(self.frame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(465, 60, 101, 41))
        font8 = QFont()
        font8.setFamilies([u"Favela-Medium"])
        font8.setPointSize(14)
        self.label_10.setFont(font8)
        self.label_10.setStyleSheet(u"background-color:rgb(41,9,133);\n"
"color:rgb(32,123,255);")
        self.textNereye_lon = QLineEdit(self.frame)
        self.textNereye_lon.setObjectName(u"textNereye_lon")
        self.textNereye_lon.setGeometry(QRect(650, 100, 180, 40))
        self.textNereye_lon.setFont(font7)
        self.textNereye_lon.setStyleSheet(u"background-color:rgb(255, 255, 255);")
        self.textNereden_lon = QLineEdit(self.frame)
        self.textNereden_lon.setObjectName(u"textNereden_lon")
        self.textNereden_lon.setGeometry(QRect(208, 100, 180, 40))
        self.textNereden_lon.setFont(font7)
        self.textNereden_lon.setStyleSheet(u"background-color:rgb(255, 255, 255);")
        self.mapwidget = QWidget(self.rightFrame)
        self.mapwidget.setObjectName(u"mapwidget")
        self.mapwidget.setGeometry(QRect(110, 280, 700, 500))
        self.mapwidget.setMinimumSize(QSize(0, 0))
        self.mapwidget.setMaximumSize(QSize(811, 611))
        self.stackedWidget.addWidget(self.page_package)
        self.page_mission = QWidget()
        self.page_mission.setObjectName(u"page_mission")
        self.connectBtn = QPushButton(self.page_mission)
        self.connectBtn.setObjectName(u"connectBtn")
        self.connectBtn.setGeometry(QRect(1520, 120, 151, 51))
        self.connectBtn.setMinimumSize(QSize(50, 40))
        font9 = QFont()
        font9.setFamilies([u"Favela-SemiBold"])
        font9.setPointSize(14)
        self.connectBtn.setFont(font9)
        self.connectBtn.setStyleSheet(u"background-color:rgba(255,255,255,0);\n"
"color:rgb(255,255,255);")
        self.connectBtn.setAutoDefault(False)
        self.connectBtn.setFlat(False)
        self.portBtn = QComboBox(self.page_mission)
        self.portBtn.addItem("")
        self.portBtn.setObjectName(u"portBtn")
        self.portBtn.setGeometry(QRect(1290, 115, 86, 61))
        self.portBtn.setFont(font8)
        self.portBtn.setStyleSheet(u"background-color:rgba(255,255,255,0);\n"
"color:rgb(32,123,255);")
        self.portBtn.setFrame(False)
        self.comBtn = QComboBox(self.page_mission)
        self.comBtn.addItem("")
        self.comBtn.addItem("")
        self.comBtn.setObjectName(u"comBtn")
        self.comBtn.setGeometry(QRect(1400, 115, 101, 61))
        self.comBtn.setFont(font8)
        self.comBtn.setStyleSheet(u"background-color:rgba(255,255,255,0);\n"
"color:rgb(32,123,255);")
        self.comBtn.setFrame(False)
        self.label_location = QLabel(self.page_mission)
        self.label_location.setObjectName(u"label_location")
        self.label_location.setGeometry(QRect(50, 110, 1080, 720))
        sizePolicy5 = QSizePolicy(QSizePolicy.Ignored, QSizePolicy.Ignored)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.label_location.sizePolicy().hasHeightForWidth())
        self.label_location.setSizePolicy(sizePolicy5)
        self.label_location.setMinimumSize(QSize(0, 0))
        self.label_location.setMaximumSize(QSize(1080, 720))
        self.label_location.setStyleSheet(u"border-radius:10px;")
        self.labelSatellite = QLabel(self.page_mission)
        self.labelSatellite.setObjectName(u"labelSatellite")
        self.labelSatellite.setGeometry(QRect(220, 758, 55, 16))
        font10 = QFont()
        font10.setPointSize(10)
        self.labelSatellite.setFont(font10)
        self.labelSatellite.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.labelFixed = QLabel(self.page_mission)
        self.labelFixed.setObjectName(u"labelFixed")
        self.labelFixed.setGeometry(QRect(220, 720, 55, 16))
        self.labelFixed.setFont(font10)
        self.labelFixed.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.labelFixed_2 = QLabel(self.page_mission)
        self.labelFixed_2.setObjectName(u"labelFixed_2")
        self.labelFixed_2.setGeometry(QRect(90, 750, 111, 31))
        font11 = QFont()
        font11.setFamilies([u"Favela-Medium"])
        font11.setPointSize(12)
        self.labelFixed_2.setFont(font11)
        self.labelFixed_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color:rgba(255,255,255,0);")
        self.labelSatellite_2 = QLabel(self.page_mission)
        self.labelSatellite_2.setObjectName(u"labelSatellite_2")
        self.labelSatellite_2.setGeometry(QRect(90, 710, 111, 31))
        self.labelSatellite_2.setFont(font11)
        self.labelSatellite_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color:rgba(255,255,255,0);")
        self.label_47 = QLabel(self.page_mission)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(1281, 360, 191, 36))
        font12 = QFont()
        font12.setFamilies([u"Favela-Medium"])
        font12.setPointSize(14)
        font12.setBold(True)
        self.label_47.setFont(font12)
        self.label_47.setStyleSheet(u"background-color:rgba(255,255,255,0);\n"
"color: rgb(32, 123, 255);")
        self.modeCheck_2 = QComboBox(self.page_mission)
        self.modeCheck_2.addItem("")
        self.modeCheck_2.addItem("")
        self.modeCheck_2.addItem("")
        self.modeCheck_2.addItem("")
        self.modeCheck_2.addItem("")
        self.modeCheck_2.addItem("")
        self.modeCheck_2.addItem("")
        self.modeCheck_2.setObjectName(u"modeCheck_2")
        self.modeCheck_2.setGeometry(QRect(1540, 364, 121, 31))
        self.modeCheck_2.setMinimumSize(QSize(50, 0))
        self.modeCheck_2.setFont(font8)
        self.modeCheck_2.setStyleSheet(u"background-color:transparent;\n"
"color:rgba(32,123,255,255);")
        self.modeCheck_2.setFrame(True)
        self.label_40 = QLabel(self.page_mission)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(1280, 250, 81, 21))
        self.label_40.setFont(font12)
        self.label_40.setStyleSheet(u"background-color:rgba(255,255,255,0);\n"
"color: rgb(32, 123, 255);")
        self.takeOffBtn = QPushButton(self.page_mission)
        self.takeOffBtn.setObjectName(u"takeOffBtn")
        self.takeOffBtn.setGeometry(QRect(1290, 620, 341, 51))
        self.takeOffBtn.setMinimumSize(QSize(0, 0))
        self.takeOffBtn.setMaximumSize(QSize(999, 999))
        self.takeOffBtn.setFont(font6)
        self.takeOffBtn.setStyleSheet(u"background-color: rgb(32, 123, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.label_35 = QLabel(self.page_mission)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(1280, 300, 131, 41))
        self.label_35.setFont(font12)
        self.label_35.setStyleSheet(u"background-color:rgba(255,255,255,0);\n"
"color: rgb(32, 123, 255);")
        self.line_HomeLocation = QLineEdit(self.page_mission)
        self.line_HomeLocation.setObjectName(u"line_HomeLocation")
        self.line_HomeLocation.setGeometry(QRect(1450, 250, 191, 22))
        self.line_HomeLocation.setFont(font10)
        self.line_HomeLocation.setStyleSheet(u"background-color:rgba(255,255,255,0);\n"
"color:rgba(32,123,255,255);")
        self.line_targetAlt = QLineEdit(self.page_mission)
        self.line_targetAlt.setObjectName(u"line_targetAlt")
        self.line_targetAlt.setGeometry(QRect(1450, 310, 191, 21))
        font13 = QFont()
        font13.setPointSize(12)
        self.line_targetAlt.setFont(font13)
        self.line_targetAlt.setStyleSheet(u"background-color:rgba(255,255,255,0);\n"
"color:rgba(32,123,255,255);")
        self.disarmBtn = QPushButton(self.page_mission)
        self.disarmBtn.setObjectName(u"disarmBtn")
        self.disarmBtn.setGeometry(QRect(1290, 710, 341, 51))
        self.disarmBtn.setMinimumSize(QSize(0, 0))
        self.disarmBtn.setMaximumSize(QSize(999, 999))
        self.disarmBtn.setFont(font6)
        self.disarmBtn.setStyleSheet(u"background-color: rgb(32, 123, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.armBtn = QPushButton(self.page_mission)
        self.armBtn.setObjectName(u"armBtn")
        self.armBtn.setGeometry(QRect(1290, 530, 341, 51))
        self.armBtn.setMinimumSize(QSize(0, 0))
        self.armBtn.setMaximumSize(QSize(999, 999))
        self.armBtn.setFont(font6)
        self.armBtn.setStyleSheet(u"background-color: rgb(32, 123, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.checkCameraOn = QCheckBox(self.page_mission)
        self.checkCameraOn.setObjectName(u"checkCameraOn")
        self.checkCameraOn.setGeometry(QRect(1370, 440, 241, 41))
        font14 = QFont()
        font14.setFamilies([u"Favela-Bold"])
        font14.setPointSize(16)
        self.checkCameraOn.setFont(font14)
        self.checkCameraOn.setStyleSheet(u"background-color:rgba(255,255,255,0);\n"
"color:rgba(32,123,255,255);")
        self.label = QLabel(self.page_mission)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(1230, 60, 461, 761))
        font15 = QFont()
        font15.setFamilies([u"Favela-Medium"])
        self.label.setFont(font15)
        self.label.setStyleSheet(u"background-color:rgba(41,9,133,200);\n"
"color:rgba(32,123,255,255);\n"
"border-radius:10px;")
        self.label_2 = QLabel(self.page_mission)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(1250, 100, 431, 91))
        self.label_2.setStyleSheet(u"background-color:rgb(18,4,62);\n"
"border-radius:10px;")
        self.labelPaketBilgiBack_4 = QLabel(self.page_mission)
        self.labelPaketBilgiBack_4.setObjectName(u"labelPaketBilgiBack_4")
        self.labelPaketBilgiBack_4.setGeometry(QRect(45, 56, 16, 31))
        self.labelPaketBilgiBack_4.setStyleSheet(u"background-color: rgb(32,123,255);")
        self.labelPaketBilgisi_4 = QLabel(self.page_mission)
        self.labelPaketBilgisi_4.setObjectName(u"labelPaketBilgisi_4")
        self.labelPaketBilgisi_4.setGeometry(QRect(70, 50, 281, 41))
        self.labelPaketBilgisi_4.setFont(font5)
        self.labelPaketBilgisi_4.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(18,4,62);")
        self.stackedWidget.addWidget(self.page_mission)
        self.label.raise_()
        self.label_2.raise_()
        self.connectBtn.raise_()
        self.portBtn.raise_()
        self.comBtn.raise_()
        self.label_location.raise_()
        self.labelFixed.raise_()
        self.label_47.raise_()
        self.modeCheck_2.raise_()
        self.label_40.raise_()
        self.takeOffBtn.raise_()
        self.label_35.raise_()
        self.line_HomeLocation.raise_()
        self.line_targetAlt.raise_()
        self.disarmBtn.raise_()
        self.armBtn.raise_()
        self.checkCameraOn.raise_()
        self.labelSatellite_2.raise_()
        self.labelFixed_2.raise_()
        self.labelPaketBilgiBack_4.raise_()
        self.labelPaketBilgisi_4.raise_()
        self.labelSatellite.raise_()
        self.page_dataFlight = QWidget()
        self.page_dataFlight.setObjectName(u"page_dataFlight")
        self.page_dataFlight.setStyleSheet(u"#page_dataFlight{\n"
"background-color: rgb(74, 16, 241);\n"
"}")
        self.label_6 = QLabel(self.page_dataFlight)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(990, 580, 160, 41))
        self.label_6.setMaximumSize(QSize(160, 150))
        font16 = QFont()
        font16.setFamilies([u"Favela-Medium"])
        font16.setPointSize(16)
        self.label_6.setFont(font16)
        self.label_6.setStyleSheet(u"color:white;")
        self.label_5 = QLabel(self.page_dataFlight)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(1400, 580, 160, 41))
        self.label_5.setMaximumSize(QSize(160, 150))
        self.label_5.setFont(font16)
        self.label_5.setStyleSheet(u"color:white;")
        self.label_43 = QLabel(self.page_dataFlight)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(140, 580, 151, 41))
        self.label_43.setMaximumSize(QSize(160, 150))
        self.label_43.setFont(font16)
        self.label_43.setStyleSheet(u"color:white;")
        self.label_45 = QLabel(self.page_dataFlight)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(540, 580, 200, 41))
        self.label_45.setMaximumSize(QSize(200, 150))
        self.label_45.setFont(font16)
        self.label_45.setStyleSheet(u"color:white;")
        self.altGauge = QWidget(self.page_dataFlight)
        self.altGauge.setObjectName(u"altGauge")
        self.altGauge.setGeometry(QRect(50, 250, 300, 300))
        self.altGauge.setMaximumSize(QSize(300, 300))
        self.groundGauge = QWidget(self.page_dataFlight)
        self.groundGauge.setObjectName(u"groundGauge")
        self.groundGauge.setGeometry(QRect(480, 250, 300, 290))
        self.groundGauge.setMaximumSize(QSize(300, 300))
        self.airSpeedGauge = QWidget(self.page_dataFlight)
        self.airSpeedGauge.setObjectName(u"airSpeedGauge")
        self.airSpeedGauge.setGeometry(QRect(1330, 250, 300, 300))
        self.airSpeedGauge.setMaximumSize(QSize(300, 300))
        self.velocityGauges = QWidget(self.page_dataFlight)
        self.velocityGauges.setObjectName(u"velocityGauges")
        self.velocityGauges.setGeometry(QRect(910, 250, 300, 300))
        self.velocityGauges.setMaximumSize(QSize(300, 300))
        self.progressBar = QProgressBar(self.page_dataFlight)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(50, 90, 401, 61))
        font17 = QFont()
        font17.setFamilies([u"Favela-Medium"])
        font17.setPointSize(24)
        self.progressBar.setFont(font17)
        self.progressBar.setStyleSheet(u"color: rgb(32, 123, 255);")
        self.progressBar.setValue(0)
        self.progressBar.setOrientation(Qt.Horizontal)
        self.progressBar.setTextDirection(QProgressBar.TopToBottom)
        self.label_3 = QLabel(self.page_dataFlight)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(60, 40, 221, 31))
        font18 = QFont()
        font18.setFamilies([u"Favela-SemiBold"])
        font18.setPointSize(12)
        self.label_3.setFont(font18)
        self.label_3.setStyleSheet(u"color:rgb(32,123,255);")
        self.label_8 = QLabel(self.page_dataFlight)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 10, 1741, 871))
        self.label_8.setStyleSheet(u"#label_8{\n"
"background-color:rgb(18,4,62);\n"
"}")
        self.stackedWidget.addWidget(self.page_dataFlight)
        self.label_8.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.label_43.raise_()
        self.label_45.raise_()
        self.altGauge.raise_()
        self.groundGauge.raise_()
        self.airSpeedGauge.raise_()
        self.velocityGauges.raise_()
        self.progressBar.raise_()
        self.label_3.raise_()
        self.page_preFlight = QWidget()
        self.page_preFlight.setObjectName(u"page_preFlight")
        self.page_preFlight.setStyleSheet(u"#page_preFlight{\n"
"background-color:rgb(18,4,62);\n"
"}")
        self.leftFrame_3 = QWidget(self.page_preFlight)
        self.leftFrame_3.setObjectName(u"leftFrame_3")
        self.leftFrame_3.setGeometry(QRect(0, 0, 831, 871))
        self.leftFrame_3.setStyleSheet(u"#leftFrame_3{\n"
"background-color: rgba(41, 9, 133,200);\n"
"}")
        self.label_26 = QLabel(self.leftFrame_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(60, 370, 261, 21))
        self.label_26.setMaximumSize(QSize(350, 16777215))
        self.label_26.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-SemiBold\";")
        self.modeCheck = QComboBox(self.leftFrame_3)
        self.modeCheck.addItem("")
        self.modeCheck.addItem("")
        self.modeCheck.addItem("")
        self.modeCheck.addItem("")
        self.modeCheck.addItem("")
        self.modeCheck.addItem("")
        self.modeCheck.addItem("")
        self.modeCheck.setObjectName(u"modeCheck")
        self.modeCheck.setGeometry(QRect(390, 300, 250, 25))
        self.modeCheck.setMinimumSize(QSize(50, 0))
        self.modeCheck.setMaximumSize(QSize(250, 16777215))
        self.modeCheck.setFont(font)
        self.modeCheck.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";")
        self.modeCheck.setFrame(True)
        self.labelTelemetry = QLabel(self.leftFrame_3)
        self.labelTelemetry.setObjectName(u"labelTelemetry")
        self.labelTelemetry.setGeometry(QRect(420, 230, 51, 21))
        self.labelTelemetry.setMaximumSize(QSize(250, 30))
        self.labelTelemetry.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";")
        self.noRadioEquip = QRadioButton(self.leftFrame_3)
        self.noRadioEquip.setObjectName(u"noRadioEquip")
        self.noRadioEquip.setGeometry(QRect(480, 370, 61, 20))
        self.noRadioEquip.setMaximumSize(QSize(250, 16777215))
        self.noRadioEquip.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";")
        self.gpsCheck = QCheckBox(self.leftFrame_3)
        self.gpsCheck.setObjectName(u"gpsCheck")
        self.gpsCheck.setGeometry(QRect(390, 160, 250, 25))
        sizePolicy2.setHeightForWidth(self.gpsCheck.sizePolicy().hasHeightForWidth())
        self.gpsCheck.setSizePolicy(sizePolicy2)
        self.gpsCheck.setMaximumSize(QSize(250, 16777215))
        self.gpsCheck.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";")
        self.label_12 = QLabel(self.leftFrame_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(60, 160, 101, 20))
        self.label_12.setMaximumSize(QSize(250, 16777215))
        self.label_12.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-SemiBold\";")
        self.label_19 = QLabel(self.leftFrame_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(60, 230, 241, 31))
        self.label_19.setMaximumSize(QSize(250, 16777215))
        self.label_19.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-SemiBold\";")
        self.label_25 = QLabel(self.leftFrame_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(60, 300, 320, 20))
        self.label_25.setMaximumSize(QSize(320, 16777215))
        self.label_25.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-SemiBold\";")
        self.yesRadioEquip = QRadioButton(self.leftFrame_3)
        self.yesRadioEquip.setObjectName(u"yesRadioEquip")
        self.yesRadioEquip.setEnabled(True)
        self.yesRadioEquip.setGeometry(QRect(390, 370, 71, 20))
        self.yesRadioEquip.setMaximumSize(QSize(250, 16777215))
        self.yesRadioEquip.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";")
        self.labelTelemetry_2 = QLabel(self.leftFrame_3)
        self.labelTelemetry_2.setObjectName(u"labelTelemetry_2")
        self.labelTelemetry_2.setGeometry(QRect(390, 230, 21, 21))
        self.labelTelemetry_2.setMaximumSize(QSize(250, 30))
        self.labelTelemetry_2.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";")
        self.switchCheck = QCheckBox(self.leftFrame_3)
        self.switchCheck.setObjectName(u"switchCheck")
        self.switchCheck.setGeometry(QRect(390, 440, 91, 20))
        self.switchCheck.setMaximumSize(QSize(250, 16777215))
        self.switchCheck.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";")
        self.label_24 = QLabel(self.leftFrame_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(60, 434, 271, 31))
        self.label_24.setMaximumSize(QSize(350, 50))
        self.label_24.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-SemiBold\";")
        self.labelPaketBilgisi_5 = QLabel(self.leftFrame_3)
        self.labelPaketBilgisi_5.setObjectName(u"labelPaketBilgisi_5")
        self.labelPaketBilgisi_5.setGeometry(QRect(85, 60, 281, 41))
        self.labelPaketBilgisi_5.setFont(font5)
        self.labelPaketBilgisi_5.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgba(18,4,62,0);")
        self.labelPaketBilgiBack_5 = QLabel(self.leftFrame_3)
        self.labelPaketBilgiBack_5.setObjectName(u"labelPaketBilgiBack_5")
        self.labelPaketBilgiBack_5.setGeometry(QRect(60, 66, 16, 31))
        self.labelPaketBilgiBack_5.setStyleSheet(u"background-color: rgb(32,123,255);")
        self.rightFrame_3 = QFrame(self.page_preFlight)
        self.rightFrame_3.setObjectName(u"rightFrame_3")
        self.rightFrame_3.setGeometry(QRect(930, 120, 581, 531))
        self.rightFrame_3.setFrameShape(QFrame.StyledPanel)
        self.rightFrame_3.setFrameShadow(QFrame.Raised)
        self.label_18 = QLabel(self.rightFrame_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 167, 300, 31))
        self.label_18.setMaximumSize(QSize(300, 50))
        self.label_18.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-SemiBold\";")
        self.label_23 = QLabel(self.rightFrame_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(30, 380, 331, 21))
        self.label_23.setMaximumSize(QSize(350, 50))
        self.label_23.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-SemiBold\";")
        self.label_21 = QLabel(self.rightFrame_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(30, 240, 250, 21))
        self.label_21.setMaximumSize(QSize(250, 50))
        self.label_21.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-SemiBold\";")
        self.label_17 = QLabel(self.rightFrame_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(30, 100, 250, 21))
        self.label_17.setMaximumSize(QSize(250, 50))
        self.label_17.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-SemiBold\";")
        self.label_16 = QLabel(self.rightFrame_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(30, 30, 250, 21))
        self.label_16.setMaximumSize(QSize(250, 50))
        self.label_16.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-SemiBold\";")
        self.label_22 = QLabel(self.rightFrame_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(30, 310, 250, 21))
        self.label_22.setMaximumSize(QSize(250, 50))
        self.label_22.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 12pt \"Favela-SemiBold\";")
        self.engineCheck = QCheckBox(self.rightFrame_3)
        self.engineCheck.setObjectName(u"engineCheck")
        self.engineCheck.setGeometry(QRect(370, 170, 91, 20))
        self.engineCheck.setMaximumSize(QSize(250, 16777215))
        self.engineCheck.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";")
        self.batteryLabel = QLabel(self.rightFrame_3)
        self.batteryLabel.setObjectName(u"batteryLabel")
        self.batteryLabel.setGeometry(QRect(390, 30, 41, 21))
        self.batteryLabel.setMaximumSize(QSize(250, 16777215))
        self.batteryLabel.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";")
        self.label_42 = QLabel(self.rightFrame_3)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(370, 30, 16, 21))
        self.label_42.setMinimumSize(QSize(0, 0))
        self.label_42.setMaximumSize(QSize(250, 16777215))
        self.label_42.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";")
        self.safetyFuseCheck = QCheckBox(self.rightFrame_3)
        self.safetyFuseCheck.setObjectName(u"safetyFuseCheck")
        self.safetyFuseCheck.setGeometry(QRect(370, 240, 91, 20))
        self.safetyFuseCheck.setMaximumSize(QSize(250, 16777215))
        self.safetyFuseCheck.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";")
        self.mechanicCheck = QCheckBox(self.rightFrame_3)
        self.mechanicCheck.setObjectName(u"mechanicCheck")
        self.mechanicCheck.setGeometry(QRect(370, 380, 91, 20))
        self.mechanicCheck.setMinimumSize(QSize(0, 20))
        self.mechanicCheck.setMaximumSize(QSize(250, 16777215))
        self.mechanicCheck.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";")
        self.cameraYesradio = QRadioButton(self.rightFrame_3)
        self.cameraYesradio.setObjectName(u"cameraYesradio")
        self.cameraYesradio.setGeometry(QRect(370, 100, 71, 16))
        self.cameraYesradio.setMaximumSize(QSize(250, 16777215))
        self.cameraYesradio.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";")
        self.cameraNoRadio = QRadioButton(self.rightFrame_3)
        self.cameraNoRadio.setObjectName(u"cameraNoRadio")
        self.cameraNoRadio.setGeometry(QRect(450, 100, 61, 16))
        self.cameraNoRadio.setMaximumSize(QSize(250, 16777215))
        self.cameraNoRadio.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";")
        self.escCheckBtn = QPushButton(self.rightFrame_3)
        self.escCheckBtn.setObjectName(u"escCheckBtn")
        self.escCheckBtn.setGeometry(QRect(360, 306, 181, 28))
        self.escCheckBtn.setMaximumSize(QSize(250, 16777215))
        self.stackedWidget.addWidget(self.page_preFlight)
        self.page_settings = QWidget()
        self.page_settings.setObjectName(u"page_settings")
        self.leftFrame_2 = QFrame(self.page_settings)
        self.leftFrame_2.setObjectName(u"leftFrame_2")
        self.leftFrame_2.setGeometry(QRect(0, 0, 291, 881))
        self.leftFrame_2.setMaximumSize(QSize(300, 16777215))
        self.leftFrame_2.setStyleSheet(u"")
        self.leftFrame_2.setFrameShape(QFrame.StyledPanel)
        self.leftFrame_2.setFrameShadow(QFrame.Raised)
        self.label_32 = QLabel(self.leftFrame_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(30, 110, 241, 30))
        self.label_32.setMaximumSize(QSize(250, 16777215))
        self.label_32.setFont(font9)
        self.label_32.setStyleSheet(u"color: rgb(255,255,255);")
        self.label_33 = QLabel(self.leftFrame_2)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(30, 290, 200, 30))
        self.label_33.setMaximumSize(QSize(200, 16777215))
        self.label_33.setFont(font9)
        self.label_33.setStyleSheet(u"color: rgb(255,255,255);\n"
"background-color:transparent;")
        self.label_34 = QLabel(self.leftFrame_2)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(30, 670, 230, 30))
        self.label_34.setMaximumSize(QSize(230, 16777215))
        self.label_34.setFont(font9)
        self.label_34.setStyleSheet(u"color: rgb(255,255,255);\n"
"background-color:transparent;")
        self.label_37 = QLabel(self.leftFrame_2)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(30, 470, 200, 30))
        self.label_37.setMaximumSize(QSize(200, 16777215))
        self.label_37.setFont(font9)
        self.label_37.setStyleSheet(u"color: rgb(255,255,255);\n"
"background-color:transparent;")
        self.label_14 = QLabel(self.leftFrame_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 105, 241, 41))
        self.label_14.setStyleSheet(u"\n"
"background-color:rgb(32,123,255);\n"
"border-radius:10px;")
        self.label_15 = QLabel(self.leftFrame_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 285, 241, 41))
        self.label_15.setStyleSheet(u"\n"
"background-color:rgb(32,123,255);\n"
"border-radius:10px;")
        self.label_20 = QLabel(self.leftFrame_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 465, 241, 41))
        self.label_20.setStyleSheet(u"\n"
"background-color:rgb(32,123,255);\n"
"border-radius:10px;")
        self.label_27 = QLabel(self.leftFrame_2)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(20, 665, 251, 41))
        self.label_27.setStyleSheet(u"\n"
"background-color:rgb(32,123,255);\n"
"border-radius:10px;")
        self.label_27.raise_()
        self.label_20.raise_()
        self.label_15.raise_()
        self.label_14.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_37.raise_()
        self.btnDisarmedMode = QPushButton(self.page_settings)
        self.btnDisarmedMode.setObjectName(u"btnDisarmedMode")
        self.btnDisarmedMode.setGeometry(QRect(1070, 70, 200, 120))
        self.btnDisarmedMode.setMinimumSize(QSize(120, 50))
        self.btnDisarmedMode.setMaximumSize(QSize(200, 120))
        self.btnDisarmedMode.setFont(font11)
        self.btnDisarmedMode.setStyleSheet(u"QPushButton {\n"
"border-radius: 10px;\n"
"background-color:rgba(74,16,241,255);\n"
"border: 3px solid #207bff;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(32,123,255);\n"
"}")
        self.btnGuideMode = QPushButton(self.page_settings)
        self.btnGuideMode.setObjectName(u"btnGuideMode")
        self.btnGuideMode.setGeometry(QRect(310, 70, 200, 120))
        self.btnGuideMode.setMinimumSize(QSize(120, 50))
        self.btnGuideMode.setMaximumSize(QSize(200, 120))
        self.btnGuideMode.setFont(font11)
        self.btnGuideMode.setStyleSheet(u"QPushButton {\n"
"border-radius: 10px;\n"
"background-color:rgba(74,16,241,255);\n"
"border: 3px solid #207bff;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(32,123,255);\n"
"}")
        self.btnAutoMode = QPushButton(self.page_settings)
        self.btnAutoMode.setObjectName(u"btnAutoMode")
        self.btnAutoMode.setGeometry(QRect(560, 70, 200, 120))
        self.btnAutoMode.setMinimumSize(QSize(120, 50))
        self.btnAutoMode.setMaximumSize(QSize(200, 120))
        self.btnAutoMode.setFont(font11)
        self.btnAutoMode.setStyleSheet(u"QPushButton {\n"
"border-radius: 10px;\n"
"background-color:rgba(74,16,241,255);\n"
"border: 3px solid #207bff;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(32,123,255);\n"
"}")
        self.btnQrtlMode = QPushButton(self.page_settings)
        self.btnQrtlMode.setObjectName(u"btnQrtlMode")
        self.btnQrtlMode.setGeometry(QRect(810, 70, 200, 120))
        self.btnQrtlMode.setMinimumSize(QSize(120, 50))
        self.btnQrtlMode.setMaximumSize(QSize(200, 120))
        self.btnQrtlMode.setFont(font11)
        self.btnQrtlMode.setStyleSheet(u"QPushButton {\n"
"border-radius: 10px;\n"
"background-color:rgba(74,16,241,255);\n"
"border: 3px solid #207bff;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(32,123,255);\n"
"}")
        self.btnLowQuality = QPushButton(self.page_settings)
        self.btnLowQuality.setObjectName(u"btnLowQuality")
        self.btnLowQuality.setGeometry(QRect(310, 240, 200, 120))
        self.btnLowQuality.setMinimumSize(QSize(120, 50))
        self.btnLowQuality.setMaximumSize(QSize(200, 120))
        self.btnLowQuality.setFont(font11)
        self.btnLowQuality.setStyleSheet(u"QPushButton {\n"
"border-radius: 10px;\n"
"background-color:rgba(74,16,241,255);\n"
"border: 3px solid #207bff;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(32,123,255);\n"
"}")
        self.label_38 = QLabel(self.page_settings)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(320, 670, 41, 31))
        self.label_38.setMaximumSize(QSize(50, 16777215))
        self.label_38.setFont(font9)
        self.label_38.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font: \"MS Shell Dlg 2\";")
        self.idLabel = QLabel(self.page_settings)
        self.idLabel.setObjectName(u"idLabel")
        self.idLabel.setGeometry(QRect(370, 670, 100, 31))
        self.idLabel.setMinimumSize(QSize(100, 0))
        self.idLabel.setMaximumSize(QSize(50, 16777215))
        font19 = QFont()
        font19.setFamilies([u"Favela-Medium"])
        font19.setPointSize(14)
        font19.setBold(False)
        font19.setItalic(False)
        font19.setUnderline(True)
        self.idLabel.setFont(font19)
        self.idLabel.setStyleSheet(u"color: rgb(32, 123, 255);\n"
"font:\"MS Shell Dlg 2\";")
        self.widget_22 = QWidget(self.page_settings)
        self.widget_22.setObjectName(u"widget_22")
        self.widget_22.setGeometry(QRect(310, 430, 201, 131))
        self.widget_22.setMaximumSize(QSize(999, 999))
        self.widget_22.setStyleSheet(u"border-image: url(:/envanter/images/img/poyrazHavacilik.png);\n"
"background-color:transparent;")
        self.btnExit = QPushButton(self.page_settings)
        self.btnExit.setObjectName(u"btnExit")
        self.btnExit.setGeometry(QRect(1550, 760, 161, 81))
        self.btnExit.setMinimumSize(QSize(0, 0))
        self.btnExit.setMaximumSize(QSize(999, 16777215))
        self.btnExit.setFont(font11)
        self.btnExit.setStyleSheet(u"QPushButton {\n"
"border-radius: 10px;\n"
"background-color:rgba(74,16,241,255);\n"
"border: 3px solid #207bff;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(32,123,255);\n"
"}")
        self.label_39 = QLabel(self.page_settings)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(660, 470, 101, 30))
        self.label_39.setMaximumSize(QSize(200, 16777215))
        self.label_39.setFont(font9)
        self.label_39.setStyleSheet(u"color: rgb(255,255,255);\n"
"background-color:transparent;")
        self.label_11 = QLabel(self.page_settings)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(780, 400, 321, 181))
        self.label_11.setStyleSheet(u"border-image: url(:/envanter/images/img/ZINKvtol.png);")
        self.label_13 = QLabel(self.page_settings)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(780, 570, 111, 21))
        font20 = QFont()
        font20.setFamilies([u"Favela-Medium"])
        font20.setPointSize(10)
        self.label_13.setFont(font20)
        self.label_13.setStyleSheet(u"color: rgb(32, 123, 255);")
        self.label_28 = QLabel(self.page_settings)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(640, 465, 301, 41))
        self.label_28.setStyleSheet(u"\n"
"background-color:rgb(32,123,255);\n"
"border-radius:10px;")
        self.stackedWidget.addWidget(self.page_settings)
        self.label_28.raise_()
        self.leftFrame_2.raise_()
        self.btnDisarmedMode.raise_()
        self.btnGuideMode.raise_()
        self.btnAutoMode.raise_()
        self.btnQrtlMode.raise_()
        self.btnLowQuality.raise_()
        self.label_38.raise_()
        self.idLabel.raise_()
        self.widget_22.raise_()
        self.btnExit.raise_()
        self.label_39.raise_()
        self.label_11.raise_()
        self.label_13.raise_()
        self.widget.raise_()
        self.titleBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(5)
        self.connectBtn.setDefault(False)
        self.modeCheck_2.setCurrentIndex(4)
        self.modeCheck.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Poyraz Havac\u0131l\u0131k", None))
        self.label_30.setText("")
        self.label_48.setText(QCoreApplication.translate("MainWindow", u",", None))
        self.btn_homePage.setText(QCoreApplication.translate("MainWindow", u" Envanter ", None))
        self.btn_package.setText(QCoreApplication.translate("MainWindow", u" Package  ", None))
        self.btn_mission.setText(QCoreApplication.translate("MainWindow", u" Mission   ", None))
        self.btn_dataFlight.setText(QCoreApplication.translate("MainWindow", u" Data F.   ", None))
        self.btn_preFlight.setText(QCoreApplication.translate("MainWindow", u" Pre Flight", None))
        self.btn_settings.setText(QCoreApplication.translate("MainWindow", u" Settings  ", None))
        self.label_29.setText("")
        self.label_31.setText("")
        self.label_36.setText("")
        self.label_41.setText("")
        self.label_44.setText("")
        self.label_46.setText("")
        self.btn_poyrazLogo.setText("")
        self.labelTitle.setText(QCoreApplication.translate("MainWindow", u"ENVANTER", None))
        self.label_7.setText("")
        self.urunpic1.setText("")
        self.urun1Sil.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.urunpic2.setText("")
        self.urun2Sil.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.urunpic3.setText("")
        self.urun3Sil.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.btn_sepeteEkle.setText(QCoreApplication.translate("MainWindow", u"Sepete Ekle", None))
        self.btn_tansiyon.setText("")
        self.btn_telefon.setText("")
        self.btn_guckaynagi.setText("")
        self.btn_tablet.setText("")
        self.btn_ilacKutusu.setText("")
        self.btn_kulaklik.setText("")
        self.btn_nebulizator.setText("")
        self.btn_boyunluk.setText("")
        self.btn_insulin.setText("")
        self.btn_kablo.setText("")
        self.btn_laptop.setText("")
        self.textisim.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u0130sim", None))
        self.textSoyad.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Soyisim", None))
        self.textTelefon.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Telefon (05**-***-**-**)", None))
        self.textGondericiGemi.setText("")
        self.textGondericiGemi.setPlaceholderText(QCoreApplication.translate("MainWindow", u"G\u00f6nderici Gemi", None))
        self.textHedefGemi.setInputMask("")
        self.textHedefGemi.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Hedef Gemi", None))
        self.labelPaketBilgisi.setText(QCoreApplication.translate("MainWindow", u"Paket Bilgisi", None))
        self.labelPaketBilgiBack.setText("")
        self.labelPaketBilgisi_2.setText(QCoreApplication.translate("MainWindow", u"Paket \u0130\u00e7eri\u011fi", None))
        self.paketurun2.setText("")
        self.paketurun1.setText("")
        self.paketurun3.setText("")
        self.btnOnayla.setText(QCoreApplication.translate("MainWindow", u"Onayla", None))
        self.labelPaketBilgiBack_2.setText("")
        self.labelPaketBilgiBack_3.setText("")
        self.labelPaketBilgisi_3.setText(QCoreApplication.translate("MainWindow", u"Rota Bilgisi", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Nereden", None))
        self.pushButton_13.setText("")
        self.textNereden_lat.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lat :", None))
        self.textNereye_lat.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lat :", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Nereye", None))
        self.textNereye_lon.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lon :", None))
        self.textNereden_lon.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lon :", None))
        self.connectBtn.setText(QCoreApplication.translate("MainWindow", u"CONNECT", None))
        self.portBtn.setItemText(0, QCoreApplication.translate("MainWindow", u"57600", None))

        self.comBtn.setItemText(0, QCoreApplication.translate("MainWindow", u"UDP\u0130N", None))
        self.comBtn.setItemText(1, QCoreApplication.translate("MainWindow", u"COM6", None))

        self.label_location.setText("")
        self.labelSatellite.setText("")
        self.labelFixed.setText("")
        self.labelFixed_2.setText(QCoreApplication.translate("MainWindow", u"Satellite :", None))
        self.labelSatellite_2.setText(QCoreApplication.translate("MainWindow", u"Fix-Type :", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Vehicle Mode: ", None))
        self.modeCheck_2.setItemText(0, QCoreApplication.translate("MainWindow", u"CHOOSE", None))
        self.modeCheck_2.setItemText(1, QCoreApplication.translate("MainWindow", u"QHover", None))
        self.modeCheck_2.setItemText(2, QCoreApplication.translate("MainWindow", u"QLand", None))
        self.modeCheck_2.setItemText(3, QCoreApplication.translate("MainWindow", u"QRTL", None))
        self.modeCheck_2.setItemText(4, QCoreApplication.translate("MainWindow", u"AUTO", None))
        self.modeCheck_2.setItemText(5, QCoreApplication.translate("MainWindow", u"GU\u0130DE", None))
        self.modeCheck_2.setItemText(6, QCoreApplication.translate("MainWindow", u"STABILIZE", None))

        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Home: ", None))
        self.takeOffBtn.setText(QCoreApplication.translate("MainWindow", u"TAKE OFF", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Target Alt: ", None))
        self.line_targetAlt.setText(QCoreApplication.translate("MainWindow", u"60", None))
        self.disarmBtn.setText(QCoreApplication.translate("MainWindow", u"DISARM", None))
        self.armBtn.setText(QCoreApplication.translate("MainWindow", u"GET ARM", None))
        self.checkCameraOn.setText(QCoreApplication.translate("MainWindow", u"CAMERA ON", None))
        self.label.setText("")
        self.label_2.setText("")
        self.labelPaketBilgiBack_4.setText("")
        self.labelPaketBilgisi_4.setText(QCoreApplication.translate("MainWindow", u"Kamera", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Kumpas", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"AirSpeed", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Alttitude", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"GroundSpeed", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Kalan Pil:", None))
        self.label_8.setText("")
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"is Ready For Arm ?  -->", None))
        self.modeCheck.setItemText(0, QCoreApplication.translate("MainWindow", u"CHOOSE", None))
        self.modeCheck.setItemText(1, QCoreApplication.translate("MainWindow", u"QHover", None))
        self.modeCheck.setItemText(2, QCoreApplication.translate("MainWindow", u"QLand", None))
        self.modeCheck.setItemText(3, QCoreApplication.translate("MainWindow", u"QRTL", None))
        self.modeCheck.setItemText(4, QCoreApplication.translate("MainWindow", u"AUTO", None))
        self.modeCheck.setItemText(5, QCoreApplication.translate("MainWindow", u"GU\u0130DE", None))
        self.modeCheck.setItemText(6, QCoreApplication.translate("MainWindow", u"STABILIZE", None))

        self.labelTelemetry.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.noRadioEquip.setText(QCoreApplication.translate("MainWindow", u"NO", None))
        self.gpsCheck.setText(QCoreApplication.translate("MainWindow", u"Ready", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"GPS -->", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Telemetry Signal -->", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Command Mode Check  -->", None))
        self.yesRadioEquip.setText(QCoreApplication.translate("MainWindow", u"YES", None))
        self.labelTelemetry_2.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.switchCheck.setText(QCoreApplication.translate("MainWindow", u"Ready", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"\u0130s switch working ? -->", None))
        self.labelPaketBilgisi_5.setText(QCoreApplication.translate("MainWindow", u"Pre Flight Verileri", None))
        self.labelPaketBilgiBack_5.setText("")
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Propeller and Engine  -->", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Mechanic System Check -->", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Safety fuse Check -->", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Is Camera Ready -->", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Battery Level -->", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"ESC Cable Check -->", None))
        self.engineCheck.setText(QCoreApplication.translate("MainWindow", u"Ready", None))
        self.batteryLabel.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.safetyFuseCheck.setText(QCoreApplication.translate("MainWindow", u"Ready", None))
        self.mechanicCheck.setText(QCoreApplication.translate("MainWindow", u"Ready", None))
        self.cameraYesradio.setText(QCoreApplication.translate("MainWindow", u"YES", None))
        self.cameraNoRadio.setText(QCoreApplication.translate("MainWindow", u"NO", None))
        self.escCheckBtn.setStyleSheet(QCoreApplication.translate("MainWindow", u"color: rgb(32, 123, 255);\n"
"font: 12pt \"Favela-Medium\";", None))
        self.escCheckBtn.setText(QCoreApplication.translate("MainWindow", u"CHECK", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Current Flight Mode:", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Camera Quality:", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"User \u0130nformation:", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Team:", None))
        self.label_14.setText("")
        self.label_15.setText("")
        self.label_20.setText("")
        self.label_27.setText("")
        self.btnDisarmedMode.setText(QCoreApplication.translate("MainWindow", u"Disarmed", None))
        self.btnGuideMode.setText(QCoreApplication.translate("MainWindow", u"Guided", None))
        self.btnAutoMode.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.btnQrtlMode.setText(QCoreApplication.translate("MainWindow", u"QRTL", None))
        self.btnLowQuality.setText(QCoreApplication.translate("MainWindow", u"1080x720", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"ID :", None))
        self.idLabel.setText(QCoreApplication.translate("MainWindow", u"ROOT", None))
        self.btnExit.setText(QCoreApplication.translate("MainWindow", u"> Log Out", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Vehicle:", None))
        self.label_11.setText("")
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"ZINK VTOL", None))
        self.label_28.setText("")
    # retranslateUi

