# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(950, 535)
        login.setMinimumSize(QtCore.QSize(949, 530))
        login.setMaximumSize(QtCore.QSize(9999, 9999))
        font = QtGui.QFont()
        font.setFamily("Favela-Medium")
        font.setPointSize(10)
        login.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/envanter/images/icon/poyrazLogo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        login.setWindowIcon(icon)
        login.setStyleSheet("#centralwidget{\n"
"    background-image: url(:/envanter/images/img/loginBG1.jpg);\n"
"    background-repeat: no-repeat;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.idtext = QtWidgets.QLineEdit(self.centralwidget)
        self.idtext.setGeometry(QtCore.QRect(310, 240, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Favela-Medium")
        font.setPointSize(11)
        self.idtext.setFont(font)
        self.idtext.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"color: rgba(32,123,255,255);")
        self.idtext.setObjectName("idtext")
        self.passtext = QtWidgets.QLineEdit(self.centralwidget)
        self.passtext.setGeometry(QtCore.QRect(310, 300, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Favela-Medium")
        font.setPointSize(12)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.passtext.setFont(font)
        self.passtext.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.passtext.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"color: rgba(32,123,255,255);")
        self.passtext.setInputMask("")
        self.passtext.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passtext.setObjectName("passtext")
        self.girisbtn = QtWidgets.QPushButton(self.centralwidget)
        self.girisbtn.setGeometry(QtCore.QRect(340, 360, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Favela-Medium")
        font.setPointSize(14)
        self.girisbtn.setFont(font)
        self.girisbtn.setStyleSheet("background-color: rgba(32,123,255,255);\n"
"border-radius: 12px;\n"
"")
        self.girisbtn.setObjectName("girisbtn")
        login.setCentralWidget(self.centralwidget)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "MainWindow"))
        self.idtext.setPlaceholderText(_translate("login", " ID"))
        self.passtext.setPlaceholderText(_translate("login", " Password"))
        self.girisbtn.setText(_translate("login", "GİRİS"))
        self.girisbtn.setShortcut(_translate("login", "Return"))
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QMainWindow()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec_())
