# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'HomePage.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QLineEdit, QMainWindow, QProgressBar,
    QPushButton, QRadioButton, QSizePolicy, QSpinBox,
    QStackedWidget, QWidget)
import img_rc
import icon_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(1180, 630)
        MainWindow.setMinimumSize(QSize(1180, 630))
        MainWindow.setMaximumSize(QSize(1180, 630))
        icon = QIcon()
        icon.addFile(u":/envanter/images/icon/poyrazLogo.ico", QSize(), QIcon.Normal, QIcon.Off)
        icon.addFile(u":/envanter/images/icon/poyrazLogo.ico", QSize(), QIcon.Normal, QIcon.On)
        icon.addFile(u":/envanter/images/icon/poyrazLogo.ico", QSize(), QIcon.Disabled, QIcon.On)
        icon.addFile(u":/envanter/images/icon/poyrazLogo.ico", QSize(), QIcon.Active, QIcon.Off)
        icon.addFile(u":/envanter/images/icon/poyrazLogo.ico", QSize(), QIcon.Active, QIcon.On)
        icon.addFile(u":/envanter/images/icon/poyrazLogo.ico", QSize(), QIcon.Selected, QIcon.Off)
        icon.addFile(u":/envanter/images/icon/poyrazLogo.ico", QSize(), QIcon.Selected, QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(Qt.LeftToRight)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(1180, 600))
        self.centralwidget.setMaximumSize(QSize(1180, 630))
        self.centralwidget.setStyleSheet(u"#centralwidget{\n"
"background-color: rgb(74, 16, 241);\n"
"}")
        self.leftMenu = QFrame(self.centralwidget)
        self.leftMenu.setObjectName(u"leftMenu")
        self.leftMenu.setGeometry(QRect(0, 0, 130, 630))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftMenu.sizePolicy().hasHeightForWidth())
        self.leftMenu.setSizePolicy(sizePolicy)
        self.leftMenu.setMinimumSize(QSize(70, 630))
        self.leftMenu.setMaximumSize(QSize(130, 630))
        self.leftMenu.setStyleSheet(u"#leftMenu{\n"
"background-color: rgb(74, 16, 241);\n"
"}")
        self.leftMenu.setFrameShape(QFrame.StyledPanel)
        self.leftMenu.setFrameShadow(QFrame.Raised)
        self.logoWidget = QWidget(self.leftMenu)
        self.logoWidget.setObjectName(u"logoWidget")
        self.logoWidget.setGeometry(QRect(1, 20, 128, 124))
        sizePolicy.setHeightForWidth(self.logoWidget.sizePolicy().hasHeightForWidth())
        self.logoWidget.setSizePolicy(sizePolicy)
        self.logoWidget.setMinimumSize(QSize(128, 124))
        self.logoWidget.setMaximumSize(QSize(128, 124))
        self.logoWidget.setSizeIncrement(QSize(0, 100))
        self.btn_poyrazLogo = QPushButton(self.logoWidget)
        self.btn_poyrazLogo.setObjectName(u"btn_poyrazLogo")
        self.btn_poyrazLogo.setGeometry(QRect(14, 10, 100, 114))
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.btn_poyrazLogo.sizePolicy().hasHeightForWidth())
        self.btn_poyrazLogo.setSizePolicy(sizePolicy1)
        self.btn_poyrazLogo.setMinimumSize(QSize(50, 100))
        self.btn_poyrazLogo.setMaximumSize(QSize(100, 16777215))
        self.btn_poyrazLogo.setSizeIncrement(QSize(130, 0))
        icon1 = QIcon()
        icon1.addFile(u":/envanter/images/icon/poyrazLogo.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_poyrazLogo.setIcon(icon1)
        self.btn_poyrazLogo.setIconSize(QSize(130, 120))
        self.btn_poyrazLogo.setFlat(True)
        self.btn_homePage = QPushButton(self.leftMenu)
        self.btn_homePage.setObjectName(u"btn_homePage")
        self.btn_homePage.setGeometry(QRect(1, 188, 128, 40))
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.btn_homePage.sizePolicy().hasHeightForWidth())
        self.btn_homePage.setSizePolicy(sizePolicy2)
        self.btn_homePage.setMinimumSize(QSize(70, 40))
        self.btn_homePage.setMaximumSize(QSize(130, 30))
        font = QFont()
        font.setFamilies([u"MS Shell Dlg 2"])
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.btn_homePage.setFont(font)
        self.btn_homePage.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        icon2 = QIcon()
        icon2.addFile(u":/icon/images/icon/anaSayfa.png", QSize(), QIcon.Normal, QIcon.Off)
        icon2.addFile(u":/icon/images/icon/anaSayfa.png", QSize(), QIcon.Normal, QIcon.On)
        icon2.addFile(u":/icon/images/icon/anaSayfa.png", QSize(), QIcon.Disabled, QIcon.Off)
        self.btn_homePage.setIcon(icon2)
        self.btn_homePage.setIconSize(QSize(50, 120))
        self.btn_homePage.setFlat(True)
        self.btn_package = QPushButton(self.leftMenu)
        self.btn_package.setObjectName(u"btn_package")
        self.btn_package.setGeometry(QRect(1, 267, 128, 40))
        sizePolicy2.setHeightForWidth(self.btn_package.sizePolicy().hasHeightForWidth())
        self.btn_package.setSizePolicy(sizePolicy2)
        self.btn_package.setMinimumSize(QSize(70, 40))
        self.btn_package.setMaximumSize(QSize(130, 30))
        self.btn_package.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        icon3 = QIcon()
        icon3.addFile(u":/icon/images/icon/um.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_package.setIcon(icon3)
        self.btn_package.setIconSize(QSize(50, 120))
        self.btn_package.setFlat(True)
        self.btn_mission = QPushButton(self.leftMenu)
        self.btn_mission.setObjectName(u"btn_mission")
        self.btn_mission.setGeometry(QRect(1, 346, 128, 40))
        sizePolicy2.setHeightForWidth(self.btn_mission.sizePolicy().hasHeightForWidth())
        self.btn_mission.setSizePolicy(sizePolicy2)
        self.btn_mission.setMinimumSize(QSize(70, 40))
        self.btn_mission.setMaximumSize(QSize(130, 30))
        self.btn_mission.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        icon4 = QIcon()
        icon4.addFile(u":/icon/images/icon/Mission.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_mission.setIcon(icon4)
        self.btn_mission.setIconSize(QSize(50, 120))
        self.btn_mission.setFlat(True)
        self.btn_dataFlight = QPushButton(self.leftMenu)
        self.btn_dataFlight.setObjectName(u"btn_dataFlight")
        self.btn_dataFlight.setGeometry(QRect(1, 425, 128, 40))
        sizePolicy2.setHeightForWidth(self.btn_dataFlight.sizePolicy().hasHeightForWidth())
        self.btn_dataFlight.setSizePolicy(sizePolicy2)
        self.btn_dataFlight.setMinimumSize(QSize(70, 40))
        self.btn_dataFlight.setMaximumSize(QSize(130, 30))
        self.btn_dataFlight.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        icon5 = QIcon()
        icon5.addFile(u":/icon/images/icon/flightdata.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_dataFlight.setIcon(icon5)
        self.btn_dataFlight.setIconSize(QSize(50, 120))
        self.btn_dataFlight.setFlat(True)
        self.btn_preFlight = QPushButton(self.leftMenu)
        self.btn_preFlight.setObjectName(u"btn_preFlight")
        self.btn_preFlight.setGeometry(QRect(1, 504, 128, 40))
        sizePolicy2.setHeightForWidth(self.btn_preFlight.sizePolicy().hasHeightForWidth())
        self.btn_preFlight.setSizePolicy(sizePolicy2)
        self.btn_preFlight.setMinimumSize(QSize(70, 40))
        self.btn_preFlight.setMaximumSize(QSize(130, 30))
        self.btn_preFlight.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        icon6 = QIcon()
        icon6.addFile(u":/icon/images/icon/preFlight.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_preFlight.setIcon(icon6)
        self.btn_preFlight.setIconSize(QSize(50, 120))
        self.btn_preFlight.setFlat(True)
        self.btn_settings = QPushButton(self.leftMenu)
        self.btn_settings.setObjectName(u"btn_settings")
        self.btn_settings.setGeometry(QRect(1, 578, 128, 30))
        sizePolicy2.setHeightForWidth(self.btn_settings.sizePolicy().hasHeightForWidth())
        self.btn_settings.setSizePolicy(sizePolicy2)
        self.btn_settings.setMinimumSize(QSize(70, 30))
        self.btn_settings.setMaximumSize(QSize(130, 30))
        self.btn_settings.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        icon7 = QIcon()
        icon7.addFile(u":/icon/images/icon/stngs.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_settings.setIcon(icon7)
        self.btn_settings.setIconSize(QSize(50, 120))
        self.btn_settings.setFlat(True)
        self.anaFrame = QFrame(self.centralwidget)
        self.anaFrame.setObjectName(u"anaFrame")
        self.anaFrame.setGeometry(QRect(130, 0, 1180, 630))
        self.anaFrame.setMinimumSize(QSize(1180, 630))
        self.anaFrame.setMaximumSize(QSize(1180, 630))
        self.anaFrame.setFrameShape(QFrame.StyledPanel)
        self.anaFrame.setFrameShadow(QFrame.Raised)
        self.titleBar = QWidget(self.anaFrame)
        self.titleBar.setObjectName(u"titleBar")
        self.titleBar.setGeometry(QRect(1, 1, 1212, 100))
        sizePolicy.setHeightForWidth(self.titleBar.sizePolicy().hasHeightForWidth())
        self.titleBar.setSizePolicy(sizePolicy)
        self.titleBar.setMinimumSize(QSize(0, 100))
        self.titleBar.setMaximumSize(QSize(16777215, 100))
        self.titleBar.setStyleSheet(u"#titleBar{\n"
"background-color: rgb(74, 16, 241);\n"
"}")
        self.btn_menu = QPushButton(self.titleBar)
        self.btn_menu.setObjectName(u"btn_menu")
        self.btn_menu.setGeometry(QRect(11, 50, 30, 39))
        self.btn_menu.setMinimumSize(QSize(30, 0))
        self.btn_menu.setMaximumSize(QSize(30, 16777215))
        self.btn_menu.setStyleSheet(u"")
        icon8 = QIcon()
        icon8.addFile(u":/icon/images/img/menuu.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_menu.setIcon(icon8)
        self.btn_menu.setIconSize(QSize(30, 30))
        self.btn_menu.setFlat(True)
        self.labelTitle = QLabel(self.titleBar)
        self.labelTitle.setObjectName(u"labelTitle")
        self.labelTitle.setGeometry(QRect(420, 30, 162, 40))
        font1 = QFont()
        font1.setPointSize(20)
        self.labelTitle.setFont(font1)
        self.labelTitle.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.labelTitle.setFrameShadow(QFrame.Plain)
        self.labelTitle.setLineWidth(0)
        self.widget = QWidget(self.anaFrame)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(1, 101, 1050, 530))
        self.widget.setMinimumSize(QSize(1050, 530))
        self.widget.setMaximumSize(QSize(1050, 530))
        self.stackedWidget = QStackedWidget(self.widget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 20, 1050, 531))
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QSize(1050, 531))
        self.stackedWidget.setMaximumSize(QSize(1050, 531))
        self.stackedWidget.setStyleSheet(u"#page_mission{\n"
"background-color:rgb(18,4,62);\n"
"}\n"
"#page_envanter{\n"
"background-color:rgb(18,4,62);\n"
"}\n"
"#page_package{\n"
"background-color:rgb(18,4,62);\n"
"}\n"
"#page_settings{\n"
"background-color:rgb(18,4,62);\n"
"}\n"
"")
        self.stackedWidget.setFrameShape(QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QFrame.Plain)
        self.page_envanter = QWidget()
        self.page_envanter.setObjectName(u"page_envanter")
        self.page_envanter.setStyleSheet(u"")
        self.rightWidget = QWidget(self.page_envanter)
        self.rightWidget.setObjectName(u"rightWidget")
        self.rightWidget.setGeometry(QRect(780, 10, 251, 491))
        self.rightWidget.setMinimumSize(QSize(205, 0))
        self.urunpic1 = QPushButton(self.rightWidget)
        self.urunpic1.setObjectName(u"urunpic1")
        self.urunpic1.setGeometry(QRect(100, 50, 150, 100))
        self.urunpic1.setMinimumSize(QSize(150, 100))
        self.urunpic1.setMaximumSize(QSize(150, 100))
        self.urunpic1.setStyleSheet(u"")
        self.urunpic1.setIconSize(QSize(20, 20))
        self.urunpic1.setFlat(True)
        self.urun1Sil = QPushButton(self.rightWidget)
        self.urun1Sil.setObjectName(u"urun1Sil")
        self.urun1Sil.setGeometry(QRect(10, 90, 40, 28))
        self.urun1Sil.setMaximumSize(QSize(40, 30))
        self.urunpic2 = QPushButton(self.rightWidget)
        self.urunpic2.setObjectName(u"urunpic2")
        self.urunpic2.setGeometry(QRect(90, 150, 150, 100))
        self.urunpic2.setMinimumSize(QSize(150, 100))
        self.urunpic2.setMaximumSize(QSize(150, 100))
        self.urunpic2.setFlat(True)
        self.urun2Sil = QPushButton(self.rightWidget)
        self.urun2Sil.setObjectName(u"urun2Sil")
        self.urun2Sil.setGeometry(QRect(10, 200, 40, 28))
        self.urun2Sil.setMaximumSize(QSize(40, 30))
        self.urunpic3 = QPushButton(self.rightWidget)
        self.urunpic3.setObjectName(u"urunpic3")
        self.urunpic3.setGeometry(QRect(90, 270, 150, 100))
        self.urunpic3.setMinimumSize(QSize(150, 100))
        self.urunpic3.setMaximumSize(QSize(150, 100))
        self.urunpic3.setStyleSheet(u"")
        self.urunpic3.setFlat(True)
        self.urun3Sil = QPushButton(self.rightWidget)
        self.urun3Sil.setObjectName(u"urun3Sil")
        self.urun3Sil.setGeometry(QRect(10, 310, 40, 28))
        self.urun3Sil.setMaximumSize(QSize(40, 30))
        self.btn_sepeteEkle = QPushButton(self.rightWidget)
        self.btn_sepeteEkle.setObjectName(u"btn_sepeteEkle")
        self.btn_sepeteEkle.setGeometry(QRect(50, 400, 181, 80))
        self.btn_sepeteEkle.setMinimumSize(QSize(0, 80))
        self.btn_sepeteEkle.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(32, 123, 255);")
        self.btn_tansiyon = QPushButton(self.page_envanter)
        self.btn_tansiyon.setObjectName(u"btn_tansiyon")
        self.btn_tansiyon.setGeometry(QRect(50, 30, 150, 130))
        self.btn_tansiyon.setMinimumSize(QSize(150, 130))
        self.btn_tansiyon.setMaximumSize(QSize(150, 16777215))
        self.btn_tansiyon.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/tansiyon aleti1.png);")
        self.btn_telefon = QPushButton(self.page_envanter)
        self.btn_telefon.setObjectName(u"btn_telefon")
        self.btn_telefon.setGeometry(QRect(590, 205, 150, 130))
        self.btn_telefon.setMinimumSize(QSize(150, 130))
        self.btn_telefon.setMaximumSize(QSize(150, 16777215))
        self.btn_telefon.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/Cep Telefonu1.jpg.png);")
        self.btn_guckaynagi = QPushButton(self.page_envanter)
        self.btn_guckaynagi.setObjectName(u"btn_guckaynagi")
        self.btn_guckaynagi.setGeometry(QRect(230, 370, 150, 130))
        self.btn_guckaynagi.setMinimumSize(QSize(150, 130))
        self.btn_guckaynagi.setMaximumSize(QSize(150, 16777215))
        self.btn_guckaynagi.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/gucKaynagi1.png);")
        self.btn_tablet = QPushButton(self.page_envanter)
        self.btn_tablet.setObjectName(u"btn_tablet")
        self.btn_tablet.setGeometry(QRect(230, 205, 150, 130))
        self.btn_tablet.setMinimumSize(QSize(150, 130))
        self.btn_tablet.setMaximumSize(QSize(150, 16777215))
        self.btn_tablet.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/Tablet1.jpg.png);")
        self.btn_tablet.setFlat(True)
        self.btn_ilacKutusu = QPushButton(self.page_envanter)
        self.btn_ilacKutusu.setObjectName(u"btn_ilacKutusu")
        self.btn_ilacKutusu.setGeometry(QRect(230, 30, 150, 130))
        self.btn_ilacKutusu.setMinimumSize(QSize(150, 130))
        self.btn_ilacKutusu.setMaximumSize(QSize(150, 16777215))
        self.btn_ilacKutusu.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/ilacKutusu1.png);")
        self.btn_kulaklik = QPushButton(self.page_envanter)
        self.btn_kulaklik.setObjectName(u"btn_kulaklik")
        self.btn_kulaklik.setGeometry(QRect(50, 205, 150, 130))
        self.btn_kulaklik.setMinimumSize(QSize(150, 130))
        self.btn_kulaklik.setMaximumSize(QSize(150, 16777215))
        self.btn_kulaklik.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/Kulaklik1.jpg.png);")
        self.btn_nebulizator = QPushButton(self.page_envanter)
        self.btn_nebulizator.setObjectName(u"btn_nebulizator")
        self.btn_nebulizator.setGeometry(QRect(590, 30, 150, 130))
        self.btn_nebulizator.setMinimumSize(QSize(150, 130))
        self.btn_nebulizator.setMaximumSize(QSize(150, 16777215))
        self.btn_nebulizator.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/Nebulizator1.png);")
        self.btn_boyunluk = QPushButton(self.page_envanter)
        self.btn_boyunluk.setObjectName(u"btn_boyunluk")
        self.btn_boyunluk.setGeometry(QRect(50, 370, 150, 130))
        self.btn_boyunluk.setMinimumSize(QSize(150, 130))
        self.btn_boyunluk.setMaximumSize(QSize(150, 16777215))
        self.btn_boyunluk.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/Medikal boyunluk1.png);")
        self.btn_insulin = QPushButton(self.page_envanter)
        self.btn_insulin.setObjectName(u"btn_insulin")
        self.btn_insulin.setGeometry(QRect(410, 30, 150, 130))
        self.btn_insulin.setMinimumSize(QSize(150, 130))
        self.btn_insulin.setMaximumSize(QSize(150, 16777215))
        self.btn_insulin.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/\u0130nsulin kalemi1.png);")
        self.btn_kablo = QPushButton(self.page_envanter)
        self.btn_kablo.setObjectName(u"btn_kablo")
        self.btn_kablo.setGeometry(QRect(410, 370, 150, 130))
        self.btn_kablo.setMinimumSize(QSize(150, 130))
        self.btn_kablo.setMaximumSize(QSize(150, 16777215))
        self.btn_kablo.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/Kablo1.png);")
        self.btn_laptop = QPushButton(self.page_envanter)
        self.btn_laptop.setObjectName(u"btn_laptop")
        self.btn_laptop.setGeometry(QRect(410, 205, 150, 130))
        self.btn_laptop.setMinimumSize(QSize(150, 130))
        self.btn_laptop.setMaximumSize(QSize(150, 16777215))
        self.btn_laptop.setStyleSheet(u"border-image: url(:/envanter/images/img/newimg/laptop1.jpg.png);")
        self.stackedWidget.addWidget(self.page_envanter)
        self.page_package = QWidget()
        self.page_package.setObjectName(u"page_package")
        self.page_package.setStyleSheet(u"")
        self.leftFrame = QFrame(self.page_package)
        self.leftFrame.setObjectName(u"leftFrame")
        self.leftFrame.setGeometry(QRect(0, 0, 1040, 520))
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.leftFrame.sizePolicy().hasHeightForWidth())
        self.leftFrame.setSizePolicy(sizePolicy3)
        self.leftFrame.setMinimumSize(QSize(400, 400))
        self.leftFrame.setMaximumSize(QSize(16777215, 520))
        self.leftFrame.setFrameShape(QFrame.StyledPanel)
        self.leftFrame.setFrameShadow(QFrame.Raised)
        self.titleFrame = QFrame(self.leftFrame)
        self.titleFrame.setObjectName(u"titleFrame")
        self.titleFrame.setGeometry(QRect(0, 0, 481, 550))
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.titleFrame.sizePolicy().hasHeightForWidth())
        self.titleFrame.setSizePolicy(sizePolicy4)
        self.titleFrame.setMinimumSize(QSize(0, 0))
        self.titleFrame.setMaximumSize(QSize(999, 999))
        self.titleFrame.setInputMethodHints(Qt.ImhNone)
        self.titleFrame.setFrameShape(QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QFrame.Raised)
        self.widget_3 = QWidget(self.titleFrame)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(10, 40, 491, 151))
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMaximumSize(QSize(999, 999))
        self.widget_3.setStyleSheet(u"#QWidget{\n"
"background-color: rgb(32,123,255);\n"
"}")
        self.textisim = QLineEdit(self.widget_3)
        self.textisim.setObjectName(u"textisim")
        self.textisim.setGeometry(QRect(10, 10, 400, 22))
        self.textisim.setStyleSheet(u"background-color:rgb(255, 255, 255);")
        self.textisim.setMaxLength(20)
        self.textSoyad = QLineEdit(self.widget_3)
        self.textSoyad.setObjectName(u"textSoyad")
        self.textSoyad.setGeometry(QRect(10, 40, 400, 22))
        self.textSoyad.setStyleSheet(u"background-color: rgb(255,255,255);")
        self.textSoyad.setMaxLength(20)
        self.textTelefon = QLineEdit(self.widget_3)
        self.textTelefon.setObjectName(u"textTelefon")
        self.textTelefon.setGeometry(QRect(10, 70, 400, 22))
        self.textTelefon.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.textTelefon.setMaxLength(11)
        self.textTelefon.setFrame(True)
        self.textGondericiGemi = QLineEdit(self.widget_3)
        self.textGondericiGemi.setObjectName(u"textGondericiGemi")
        self.textGondericiGemi.setGeometry(QRect(10, 100, 400, 22))
        self.textGondericiGemi.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.textGondericiGemi.setMaxLength(20)
        self.textHedefGemi = QLineEdit(self.widget_3)
        self.textHedefGemi.setObjectName(u"textHedefGemi")
        self.textHedefGemi.setGeometry(QRect(10, 130, 400, 22))
        self.textHedefGemi.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.textHedefGemi.setInputMethodHints(Qt.ImhNone)
        self.textHedefGemi.setMaxLength(20)
        self.textHedefGemi.setFrame(True)
        self.frame_4 = QFrame(self.titleFrame)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 0, 200, 41))
        self.frame_4.setMinimumSize(QSize(200, 41))
        self.frame_4.setMaximumSize(QSize(200, 41))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.labelPaketBilgisi = QLabel(self.frame_4)
        self.labelPaketBilgisi.setObjectName(u"labelPaketBilgisi")
        self.labelPaketBilgisi.setGeometry(QRect(10, 0, 141, 31))
        self.labelPaketBilgisi.setStyleSheet(u"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(18,4,62);")
        self.labelPaketBilgiBack = QLabel(self.frame_4)
        self.labelPaketBilgiBack.setObjectName(u"labelPaketBilgiBack")
        self.labelPaketBilgiBack.setGeometry(QRect(10, 10, 171, 30))
        self.labelPaketBilgiBack.setStyleSheet(u"background-color: rgb(32,123,255);")
        self.labelPaketBilgiBack.raise_()
        self.labelPaketBilgisi.raise_()
        self.labelPaketBilgisi_2 = QLabel(self.titleFrame)
        self.labelPaketBilgisi_2.setObjectName(u"labelPaketBilgisi_2")
        self.labelPaketBilgisi_2.setGeometry(QRect(20, 200, 141, 31))
        self.labelPaketBilgisi_2.setStyleSheet(u"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(18,4,62);")
        self.labelPaketBilgiBack_2 = QLabel(self.titleFrame)
        self.labelPaketBilgiBack_2.setObjectName(u"labelPaketBilgiBack_2")
        self.labelPaketBilgiBack_2.setGeometry(QRect(20, 200, 241, 41))
        self.labelPaketBilgiBack_2.setStyleSheet(u"background-color: rgb(32,123,255);")
        self.frame_15 = QFrame(self.titleFrame)
        self.frame_15.setObjectName(u"frame_15")
        self.frame_15.setGeometry(QRect(20, 250, 251, 271))
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setFrameShape(QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.frame_15)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(150, 230, 81, 20))
        self.label_4.setMaximumSize(QSize(160, 20))
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label = QLabel(self.frame_15)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 105, 81, 16))
        self.label.setMaximumSize(QSize(160, 20))
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_2 = QLabel(self.frame_15)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(150, 105, 81, 16))
        self.label_2.setMaximumSize(QSize(160, 20))
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.paketurun4 = QPushButton(self.frame_15)
        self.paketurun4.setObjectName(u"paketurun4")
        self.paketurun4.setGeometry(QRect(135, 130, 100, 100))
        self.paketurun4.setMaximumSize(QSize(500, 500))
        self.paketurun4.setStyleSheet(u"QPushButton{\n"
"background-color:rgba(80, 70, 230,150);\n"
"border-radius:10px;\n"
"}")
        self.paketurun4.setFlat(False)
        self.paketurun2 = QPushButton(self.frame_15)
        self.paketurun2.setObjectName(u"paketurun2")
        self.paketurun2.setGeometry(QRect(135, 0, 100, 100))
        self.paketurun2.setMaximumSize(QSize(500, 500))
        self.paketurun2.setStyleSheet(u"QPushButton{\n"
"background-color:rgba(80, 70, 230,150);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.paketurun2.setFlat(False)
        self.paketurun1 = QPushButton(self.frame_15)
        self.paketurun1.setObjectName(u"paketurun1")
        self.paketurun1.setGeometry(QRect(5, 0, 100, 100))
        self.paketurun1.setMaximumSize(QSize(500, 500))
        self.paketurun1.setStyleSheet(u"QPushButton{\n"
"background-color:rgba(80, 70, 230,150);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.paketurun1.setFlat(False)
        self.label_3 = QLabel(self.frame_15)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 230, 81, 20))
        self.label_3.setMaximumSize(QSize(160, 20))
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.paketurun3 = QPushButton(self.frame_15)
        self.paketurun3.setObjectName(u"paketurun3")
        self.paketurun3.setGeometry(QRect(5, 130, 100, 100))
        self.paketurun3.setMaximumSize(QSize(500, 500))
        self.paketurun3.setStyleSheet(u"QPushButton{\n"
"background-color:rgba(80, 70, 230,150);\n"
"border-radius:10px;\n"
"}")
        self.paketurun3.setFlat(False)
        self.btnOnayla = QPushButton(self.titleFrame)
        self.btnOnayla.setObjectName(u"btnOnayla")
        self.btnOnayla.setGeometry(QRect(370, 440, 111, 51))
        self.btnOnayla.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(32, 123, 255);\n"
"color: rgb(255, 255, 255);")
        self.widget_3.raise_()
        self.frame_4.raise_()
        self.labelPaketBilgiBack_2.raise_()
        self.labelPaketBilgisi_2.raise_()
        self.frame_15.raise_()
        self.btnOnayla.raise_()
        self.rightFrame = QFrame(self.leftFrame)
        self.rightFrame.setObjectName(u"rightFrame")
        self.rightFrame.setGeometry(QRect(490, 0, 559, 521))
        sizePolicy3.setHeightForWidth(self.rightFrame.sizePolicy().hasHeightForWidth())
        self.rightFrame.setSizePolicy(sizePolicy3)
        self.rightFrame.setMinimumSize(QSize(559, 521))
        self.rightFrame.setMaximumSize(QSize(559, 521))
        self.rightFrame.setStyleSheet(u"QWidget{\n"
"background-color: rgb(41, 9, 133);\n"
"}")
        self.rightFrame.setFrameShape(QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QFrame.Raised)
        self.frame = QFrame(self.rightFrame)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(6, 11, 552, 120))
        self.frame.setMinimumSize(QSize(552, 120))
        self.frame.setMaximumSize(QSize(999, 999))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.labelPaketBilgiBack_3 = QLabel(self.frame)
        self.labelPaketBilgiBack_3.setObjectName(u"labelPaketBilgiBack_3")
        self.labelPaketBilgiBack_3.setGeometry(QRect(20, 0, 160, 41))
        self.labelPaketBilgiBack_3.setStyleSheet(u"background-color: rgb(32,123,255);")
        self.labelPaketBilgisi_3 = QLabel(self.frame)
        self.labelPaketBilgisi_3.setObjectName(u"labelPaketBilgisi_3")
        self.labelPaketBilgisi_3.setGeometry(QRect(20, 0, 141, 31))
        self.labelPaketBilgisi_3.setStyleSheet(u"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(18,4,62);")
        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(50, 50, 81, 16))
        self.label_9.setStyleSheet(u"background-color:rgb(41,9,133);\n"
"color:rgb(32,123,255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_9.setTextFormat(Qt.PlainText)
        self.pushButton_13 = QPushButton(self.frame)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(240, 80, 51, 28))
        icon9 = QIcon()
        icon9.addFile(u":/icon/images/icon/Katman 11.png", QSize(), QIcon.Normal, QIcon.Off)
        icon9.addFile(u":/icon/images/icon/Katman 11.png", QSize(), QIcon.Normal, QIcon.On)
        self.pushButton_13.setIcon(icon9)
        self.pushButton_13.setIconSize(QSize(40, 40))
        self.pushButton_13.setFlat(True)
        self.labelPaketBilgiBack_4 = QLabel(self.frame)
        self.labelPaketBilgiBack_4.setObjectName(u"labelPaketBilgiBack_4")
        self.labelPaketBilgiBack_4.setGeometry(QRect(20, 80, 201, 31))
        self.labelPaketBilgiBack_4.setStyleSheet(u"background-color: rgb(32,123,255);")
        self.labelPaketBilgiBack_5 = QLabel(self.frame)
        self.labelPaketBilgiBack_5.setObjectName(u"labelPaketBilgiBack_5")
        self.labelPaketBilgiBack_5.setGeometry(QRect(320, 80, 201, 31))
        self.labelPaketBilgiBack_5.setStyleSheet(u"background-color: rgb(32,123,255);")
        self.textNereden_lat = QLineEdit(self.frame)
        self.textNereden_lat.setObjectName(u"textNereden_lat")
        self.textNereden_lat.setGeometry(QRect(15, 75, 100, 25))
        self.textNereden_lat.setStyleSheet(u"background-color:rgb(255, 255, 255);")
        self.textNereye_lat = QLineEdit(self.frame)
        self.textNereye_lat.setObjectName(u"textNereye_lat")
        self.textNereye_lat.setGeometry(QRect(315, 75, 100, 25))
        self.textNereye_lat.setStyleSheet(u"background-color:rgb(255, 255, 255);")
        self.label_10 = QLabel(self.frame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(350, 40, 81, 16))
        self.label_10.setStyleSheet(u"background-color:rgb(41,9,133);\n"
"color:rgb(32,123,255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.textNereden_lon = QLineEdit(self.frame)
        self.textNereden_lon.setObjectName(u"textNereden_lon")
        self.textNereden_lon.setGeometry(QRect(118, 75, 100, 25))
        self.textNereden_lon.setStyleSheet(u"background-color:rgb(255, 255, 255);")
        self.textNereye_lon = QLineEdit(self.frame)
        self.textNereye_lon.setObjectName(u"textNereye_lon")
        self.textNereye_lon.setGeometry(QRect(418, 75, 100, 25))
        self.textNereye_lon.setStyleSheet(u"background-color:rgb(255, 255, 255);")
        self.mapwidget = QWidget(self.rightFrame)
        self.mapwidget.setObjectName(u"mapwidget")
        self.mapwidget.setGeometry(QRect(29, 150, 500, 370))
        self.mapwidget.setMinimumSize(QSize(0, 0))
        self.mapwidget.setMaximumSize(QSize(500, 370))
        self.stackedWidget.addWidget(self.page_package)
        self.page_mission = QWidget()
        self.page_mission.setObjectName(u"page_mission")
        self.frame_missionSetting = QFrame(self.page_mission)
        self.frame_missionSetting.setObjectName(u"frame_missionSetting")
        self.frame_missionSetting.setGeometry(QRect(780, 50, 311, 471))
        self.frame_missionSetting.setMaximumSize(QSize(999, 16777215))
        self.frame_missionSetting.setFrameShape(QFrame.StyledPanel)
        self.frame_missionSetting.setFrameShadow(QFrame.Raised)
        self.frame_20 = QFrame(self.frame_missionSetting)
        self.frame_20.setObjectName(u"frame_20")
        self.frame_20.setGeometry(QRect(1, 1, 241, 31))
        self.frame_20.setMaximumSize(QSize(16777215, 50))
        self.frame_20.setFrameShape(QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QFrame.Raised)
        self.label_40 = QLabel(self.frame_20)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(10, 12, 61, 21))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.label_40.setFont(font2)
        self.label_40.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_HomeLocation = QLineEdit(self.frame_20)
        self.line_HomeLocation.setObjectName(u"line_HomeLocation")
        self.line_HomeLocation.setGeometry(QRect(90, 10, 141, 22))
        self.frame_19 = QFrame(self.frame_missionSetting)
        self.frame_19.setObjectName(u"frame_19")
        self.frame_19.setGeometry(QRect(10, 50, 251, 41))
        self.frame_19.setMaximumSize(QSize(16777215, 50))
        self.frame_19.setFrameShape(QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QFrame.Raised)
        self.label_35 = QLabel(self.frame_19)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(0, 12, 95, 21))
        self.label_35.setFont(font2)
        self.label_35.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_targetAlt = QLineEdit(self.frame_19)
        self.line_targetAlt.setObjectName(u"line_targetAlt")
        self.line_targetAlt.setGeometry(QRect(120, 10, 101, 21))
        self.frame_23 = QFrame(self.frame_missionSetting)
        self.frame_23.setObjectName(u"frame_23")
        self.frame_23.setGeometry(QRect(1, 101, 247, 41))
        self.frame_23.setMaximumSize(QSize(16777215, 50))
        self.frame_23.setFrameShape(QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QFrame.Raised)
        self.label_44 = QLabel(self.frame_23)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(12, 12, 124, 21))
        self.label_44.setFont(font2)
        self.label_44.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_HomeLocation_2 = QLineEdit(self.frame_23)
        self.line_HomeLocation_2.setObjectName(u"line_HomeLocation_2")
        self.line_HomeLocation_2.setGeometry(QRect(140, 10, 92, 22))
        self.frame_26 = QFrame(self.frame_missionSetting)
        self.frame_26.setObjectName(u"frame_26")
        self.frame_26.setGeometry(QRect(1, 151, 247, 41))
        self.frame_26.setMaximumSize(QSize(16777215, 50))
        self.frame_26.setFrameShape(QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QFrame.Raised)
        self.label_46 = QLabel(self.frame_26)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(12, 12, 124, 21))
        self.label_46.setFont(font2)
        self.label_46.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_HomeLocation_3 = QLineEdit(self.frame_26)
        self.line_HomeLocation_3.setObjectName(u"line_HomeLocation_3")
        self.line_HomeLocation_3.setGeometry(QRect(140, 10, 92, 22))
        self.frame_27 = QFrame(self.frame_missionSetting)
        self.frame_27.setObjectName(u"frame_27")
        self.frame_27.setGeometry(QRect(1, 201, 247, 41))
        self.frame_27.setMaximumSize(QSize(16777215, 60))
        self.frame_27.setFrameShape(QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QFrame.Raised)
        self.label_47 = QLabel(self.frame_27)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(12, 6, 122, 36))
        self.label_47.setFont(font2)
        self.label_47.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.modeCheck_2 = QComboBox(self.frame_27)
        self.modeCheck_2.addItem("")
        self.modeCheck_2.addItem("")
        self.modeCheck_2.addItem("")
        self.modeCheck_2.addItem("")
        self.modeCheck_2.setObjectName(u"modeCheck_2")
        self.modeCheck_2.setGeometry(QRect(140, 10, 94, 27))
        font3 = QFont()
        font3.setPointSize(10)
        self.modeCheck_2.setFont(font3)
        self.modeCheck_2.setStyleSheet(u"")
        self.modeCheck_2.setFrame(False)
        self.checkCameraOn = QCheckBox(self.frame_missionSetting)
        self.checkCameraOn.setObjectName(u"checkCameraOn")
        self.checkCameraOn.setGeometry(QRect(10, 270, 131, 20))
        self.checkCameraOn.setFont(font3)
        self.checkCameraOn.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.armBtn = QPushButton(self.frame_missionSetting)
        self.armBtn.setObjectName(u"armBtn")
        self.armBtn.setGeometry(QRect(60, 320, 141, 51))
        self.armBtn.setMinimumSize(QSize(0, 0))
        self.armBtn.setMaximumSize(QSize(999, 999))
        font4 = QFont()
        font4.setFamilies([u"MS Shell Dlg 2"])
        font4.setPointSize(12)
        font4.setBold(False)
        font4.setItalic(False)
        self.armBtn.setFont(font4)
        self.armBtn.setStyleSheet(u"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(32, 123, 255);\n"
"color: rgb(255, 255, 255);")
        self.checkCameraOff = QCheckBox(self.frame_missionSetting)
        self.checkCameraOff.setObjectName(u"checkCameraOff")
        self.checkCameraOff.setGeometry(QRect(130, 270, 131, 20))
        self.checkCameraOff.setFont(font3)
        self.checkCameraOff.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.takeOffBtn = QPushButton(self.frame_missionSetting)
        self.takeOffBtn.setObjectName(u"takeOffBtn")
        self.takeOffBtn.setGeometry(QRect(60, 400, 141, 51))
        self.takeOffBtn.setMinimumSize(QSize(0, 0))
        self.takeOffBtn.setMaximumSize(QSize(999, 999))
        self.takeOffBtn.setFont(font4)
        self.takeOffBtn.setStyleSheet(u"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(32, 123, 255);\n"
"color: rgb(255, 255, 255);")
        self.connectBtn = QPushButton(self.page_mission)
        self.connectBtn.setObjectName(u"connectBtn")
        self.connectBtn.setGeometry(QRect(900, 0, 141, 40))
        self.connectBtn.setMinimumSize(QSize(50, 40))
        font5 = QFont()
        font5.setPointSize(12)
        self.connectBtn.setFont(font5)
        self.connectBtn.setStyleSheet(u"")
        self.connectBtn.setAutoDefault(False)
        self.connectBtn.setFlat(False)
        self.portBtn = QComboBox(self.page_mission)
        self.portBtn.addItem("")
        self.portBtn.setObjectName(u"portBtn")
        self.portBtn.setGeometry(QRect(710, 2, 86, 36))
        font6 = QFont()
        font6.setPointSize(15)
        self.portBtn.setFont(font6)
        self.portBtn.setFrame(False)
        self.comBtn = QComboBox(self.page_mission)
        self.comBtn.addItem("")
        self.comBtn.setObjectName(u"comBtn")
        self.comBtn.setGeometry(QRect(800, 2, 96, 36))
        self.comBtn.setFont(font6)
        self.comBtn.setFrame(False)
        self.label_location = QLabel(self.page_mission)
        self.label_location.setObjectName(u"label_location")
        self.label_location.setGeometry(QRect(10, 10, 640, 480))
        sizePolicy5 = QSizePolicy(QSizePolicy.Ignored, QSizePolicy.Ignored)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.label_location.sizePolicy().hasHeightForWidth())
        self.label_location.setSizePolicy(sizePolicy5)
        self.label_location.setMinimumSize(QSize(0, 0))
        self.label_location.setMaximumSize(QSize(720, 1080))
        self.label_location.setStyleSheet(u"")
        self.labelSatellite = QLabel(self.page_mission)
        self.labelSatellite.setObjectName(u"labelSatellite")
        self.labelSatellite.setGeometry(QRect(100, 400, 55, 16))
        self.labelSatellite.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.labelFixed = QLabel(self.page_mission)
        self.labelFixed.setObjectName(u"labelFixed")
        self.labelFixed.setGeometry(QRect(100, 430, 55, 16))
        self.labelFixed.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.labelFixed_2 = QLabel(self.page_mission)
        self.labelFixed_2.setObjectName(u"labelFixed_2")
        self.labelFixed_2.setGeometry(QRect(30, 430, 61, 16))
        self.labelFixed_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.labelSatellite_2 = QLabel(self.page_mission)
        self.labelSatellite_2.setObjectName(u"labelSatellite_2")
        self.labelSatellite_2.setGeometry(QRect(30, 400, 61, 16))
        self.labelSatellite_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.stackedWidget.addWidget(self.page_mission)
        self.page_dataFlight = QWidget()
        self.page_dataFlight.setObjectName(u"page_dataFlight")
        self.page_dataFlight.setStyleSheet(u"#page_dataFlight{\n"
"background-color: rgb(74, 16, 241);\n"
"}")
        self.label_6 = QLabel(self.page_dataFlight)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(90, 450, 31, 20))
        self.label_6.setFont(font3)
        self.label_6.setStyleSheet(u"color:white;")
        self.label_5 = QLabel(self.page_dataFlight)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(550, 200, 80, 20))
        self.label_5.setMaximumSize(QSize(80, 16777215))
        self.label_5.setFont(font3)
        self.label_5.setStyleSheet(u"color:white;")
        self.label_43 = QLabel(self.page_dataFlight)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(70, 200, 80, 20))
        self.label_43.setMaximumSize(QSize(80, 16777215))
        self.label_43.setFont(font3)
        self.label_43.setStyleSheet(u"color:white;")
        self.label_45 = QLabel(self.page_dataFlight)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(310, 200, 80, 20))
        self.label_45.setMaximumSize(QSize(80, 16777215))
        self.label_45.setFont(font3)
        self.label_45.setStyleSheet(u"color:white;")
        self.label_11 = QLabel(self.page_dataFlight)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(320, 450, 41, 20))
        self.label_11.setFont(font3)
        self.label_11.setStyleSheet(u"color:white;")
        self.label_28 = QLabel(self.page_dataFlight)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(560, 450, 41, 20))
        self.label_28.setMaximumSize(QSize(80, 16777215))
        self.label_28.setFont(font3)
        self.label_28.setStyleSheet(u"color:white;")
        self.altGauge = QWidget(self.page_dataFlight)
        self.altGauge.setObjectName(u"altGauge")
        self.altGauge.setGeometry(QRect(0, 0, 200, 200))
        self.groundGauge = QWidget(self.page_dataFlight)
        self.groundGauge.setObjectName(u"groundGauge")
        self.groundGauge.setGeometry(QRect(240, 0, 200, 200))
        self.airSpeedGauge = QWidget(self.page_dataFlight)
        self.airSpeedGauge.setObjectName(u"airSpeedGauge")
        self.airSpeedGauge.setGeometry(QRect(480, 0, 200, 200))
        self.rollGauges = QWidget(self.page_dataFlight)
        self.rollGauges.setObjectName(u"rollGauges")
        self.rollGauges.setGeometry(QRect(0, 250, 200, 200))
        self.yawGauge = QWidget(self.page_dataFlight)
        self.yawGauge.setObjectName(u"yawGauge")
        self.yawGauge.setGeometry(QRect(240, 250, 200, 200))
        self.pitchGauge = QWidget(self.page_dataFlight)
        self.pitchGauge.setObjectName(u"pitchGauge")
        self.pitchGauge.setGeometry(QRect(480, 250, 200, 200))
        self.progressBar = QProgressBar(self.page_dataFlight)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(770, 20, 221, 61))
        self.progressBar.setValue(0)
        self.progressBar.setOrientation(Qt.Horizontal)
        self.progressBar.setTextDirection(QProgressBar.TopToBottom)
        self.stackedWidget.addWidget(self.page_dataFlight)
        self.page_preFlight = QWidget()
        self.page_preFlight.setObjectName(u"page_preFlight")
        self.page_preFlight.setStyleSheet(u"#page_preFlight{\n"
"background-color:rgb(18,4,62);\n"
"}")
        self.leftFrame_3 = QWidget(self.page_preFlight)
        self.leftFrame_3.setObjectName(u"leftFrame_3")
        self.leftFrame_3.setGeometry(QRect(0, 0, 525, 531))
        self.leftFrame_3.setStyleSheet(u"#leftFrame_3{\n"
"background-color: rgba(41, 9, 133,200);\n"
"}")
        self.label_26 = QLabel(self.leftFrame_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(80, 400, 175, 21))
        self.label_26.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.modeCheck = QComboBox(self.leftFrame_3)
        self.modeCheck.addItem("")
        self.modeCheck.addItem("")
        self.modeCheck.addItem("")
        self.modeCheck.addItem("")
        self.modeCheck.setObjectName(u"modeCheck")
        self.modeCheck.setGeometry(QRect(300, 250, 98, 25))
        self.modeCheck.setMinimumSize(QSize(50, 0))
        self.modeCheck.setFont(font3)
        self.modeCheck.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);")
        self.modeCheck.setFrame(True)
        self.labelTelemetry = QLabel(self.leftFrame_3)
        self.labelTelemetry.setObjectName(u"labelTelemetry")
        self.labelTelemetry.setGeometry(QRect(300, 100, 49, 21))
        self.labelTelemetry.setMaximumSize(QSize(16777215, 30))
        self.labelTelemetry.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.readyChech = QCheckBox(self.leftFrame_3)
        self.readyChech.setObjectName(u"readyChech")
        self.readyChech.setEnabled(False)
        self.readyChech.setGeometry(QRect(300, 330, 91, 25))
        self.readyChech.setStyleSheet(u"background-color:transparent;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.readyChech.setTristate(False)
        self.label_13 = QLabel(self.leftFrame_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(80, 170, 161, 21))
        self.label_13.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.noRadioEquip = QRadioButton(self.leftFrame_3)
        self.noRadioEquip.setObjectName(u"noRadioEquip")
        self.noRadioEquip.setGeometry(QRect(390, 400, 50, 20))
        self.noRadioEquip.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.gpsCheck = QCheckBox(self.leftFrame_3)
        self.gpsCheck.setObjectName(u"gpsCheck")
        self.gpsCheck.setGeometry(QRect(300, 30, 73, 25))
        sizePolicy1.setHeightForWidth(self.gpsCheck.sizePolicy().hasHeightForWidth())
        self.gpsCheck.setSizePolicy(sizePolicy1)
        self.gpsCheck.setStyleSheet(u"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color:transparent;")
        self.label_12 = QLabel(self.leftFrame_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(80, 30, 58, 20))
        self.label_12.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_19 = QLabel(self.leftFrame_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(80, 100, 153, 21))
        self.label_19.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_25 = QLabel(self.leftFrame_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(80, 250, 202, 20))
        self.label_25.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_14 = QLabel(self.leftFrame_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(80, 330, 101, 16))
        self.label_14.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.yesRadioEquip = QRadioButton(self.leftFrame_3)
        self.yesRadioEquip.setObjectName(u"yesRadioEquip")
        self.yesRadioEquip.setEnabled(True)
        self.yesRadioEquip.setGeometry(QRect(300, 400, 56, 20))
        self.yesRadioEquip.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.waypointSpin = QSpinBox(self.leftFrame_3)
        self.waypointSpin.setObjectName(u"waypointSpin")
        self.waypointSpin.setGeometry(QRect(300, 170, 71, 20))
        self.waypointSpin.setFocusPolicy(Qt.NoFocus)
        self.waypointSpin.setStyleSheet(u"background-color:transparent;")
        self.label_48 = QLabel(self.leftFrame_3)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(140, 460, 231, 31))
        self.label_48.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(85, 170, 0);\n"
"font: 75 20pt \"MS Shell Dlg 2\";")
        self.rightFrame_3 = QFrame(self.page_preFlight)
        self.rightFrame_3.setObjectName(u"rightFrame_3")
        self.rightFrame_3.setGeometry(QRect(525, 0, 525, 531))
        self.rightFrame_3.setFrameShape(QFrame.StyledPanel)
        self.rightFrame_3.setFrameShadow(QFrame.Raised)
        self.label_24 = QLabel(self.rightFrame_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(30, 380, 172, 21))
        self.label_24.setMaximumSize(QSize(16777215, 50))
        self.label_24.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_18 = QLabel(self.rightFrame_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 140, 186, 21))
        self.label_18.setMaximumSize(QSize(16777215, 50))
        self.label_18.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_23 = QLabel(self.rightFrame_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(30, 320, 206, 21))
        self.label_23.setMaximumSize(QSize(16777215, 50))
        self.label_23.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_21 = QLabel(self.rightFrame_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(30, 200, 160, 21))
        self.label_21.setMaximumSize(QSize(16777215, 50))
        self.label_21.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_17 = QLabel(self.rightFrame_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(30, 90, 156, 21))
        self.label_17.setMaximumSize(QSize(16777215, 50))
        self.label_17.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_16 = QLabel(self.rightFrame_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(30, 30, 126, 21))
        self.label_16.setMaximumSize(QSize(16777215, 50))
        self.label_16.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_22 = QLabel(self.rightFrame_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(30, 260, 153, 21))
        self.label_22.setMaximumSize(QSize(16777215, 50))
        self.label_22.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.escCableCheck = QCheckBox(self.rightFrame_3)
        self.escCableCheck.setObjectName(u"escCableCheck")
        self.escCableCheck.setGeometry(QRect(330, 260, 62, 20))
        self.escCableCheck.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.engineCheck = QCheckBox(self.rightFrame_3)
        self.engineCheck.setObjectName(u"engineCheck")
        self.engineCheck.setGeometry(QRect(330, 140, 62, 20))
        self.engineCheck.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.batteryLabel = QLabel(self.rightFrame_3)
        self.batteryLabel.setObjectName(u"batteryLabel")
        self.batteryLabel.setGeometry(QRect(350, 30, 27, 21))
        self.batteryLabel.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.switchCheck = QCheckBox(self.rightFrame_3)
        self.switchCheck.setObjectName(u"switchCheck")
        self.switchCheck.setGeometry(QRect(330, 380, 62, 20))
        self.switchCheck.setStyleSheet(u"background-color:transparent;\n"
"color:white")
        self.label_42 = QLabel(self.rightFrame_3)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(330, 30, 30, 21))
        self.label_42.setMinimumSize(QSize(0, 0))
        self.label_42.setMaximumSize(QSize(30, 16777215))
        self.label_42.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.safetyFuseCheck = QCheckBox(self.rightFrame_3)
        self.safetyFuseCheck.setObjectName(u"safetyFuseCheck")
        self.safetyFuseCheck.setGeometry(QRect(330, 200, 62, 20))
        self.safetyFuseCheck.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.mechanicCheck = QCheckBox(self.rightFrame_3)
        self.mechanicCheck.setObjectName(u"mechanicCheck")
        self.mechanicCheck.setGeometry(QRect(330, 320, 62, 20))
        self.mechanicCheck.setMinimumSize(QSize(0, 20))
        self.mechanicCheck.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cameraYesradio = QRadioButton(self.rightFrame_3)
        self.cameraYesradio.setObjectName(u"cameraYesradio")
        self.cameraYesradio.setGeometry(QRect(330, 90, 61, 16))
        self.cameraYesradio.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background-color:transparent;")
        self.cameraNoRadio = QRadioButton(self.rightFrame_3)
        self.cameraNoRadio.setObjectName(u"cameraNoRadio")
        self.cameraNoRadio.setGeometry(QRect(420, 90, 51, 16))
        self.cameraNoRadio.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color:transparent;")
        self.label_49 = QLabel(self.rightFrame_3)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(140, 460, 231, 31))
        self.label_49.setStyleSheet(u"background-color:transparent;\n"
"color: rgb(85, 170, 0);\n"
"font: 75 20pt \"MS Shell Dlg 2\";")
        self.stackedWidget.addWidget(self.page_preFlight)
        self.page_settings = QWidget()
        self.page_settings.setObjectName(u"page_settings")
        self.leftFrame_2 = QFrame(self.page_settings)
        self.leftFrame_2.setObjectName(u"leftFrame_2")
        self.leftFrame_2.setGeometry(QRect(0, 0, 241, 531))
        self.leftFrame_2.setMaximumSize(QSize(300, 16777215))
        self.leftFrame_2.setStyleSheet(u"")
        self.leftFrame_2.setFrameShape(QFrame.StyledPanel)
        self.leftFrame_2.setFrameShadow(QFrame.Raised)
        self.label_32 = QLabel(self.leftFrame_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(31, 40, 203, 30))
        font7 = QFont()
        font7.setFamilies([u"Favela-Medium"])
        font7.setPointSize(12)
        self.label_32.setFont(font7)
        self.label_32.setStyleSheet(u"color: rgb(32,123,255);\n"
"background-color:transparent;")
        self.label_33 = QLabel(self.leftFrame_2)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(31, 130, 158, 30))
        self.label_33.setFont(font7)
        self.label_33.setStyleSheet(u"color: rgb(32,123,255);\n"
"background-color:transparent;")
        self.label_34 = QLabel(self.leftFrame_2)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(31, 210, 173, 30))
        self.label_34.setFont(font7)
        self.label_34.setStyleSheet(u"color: rgb(32,123,255);\n"
"background-color:transparent;")
        self.label_36 = QLabel(self.leftFrame_2)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(31, 300, 137, 30))
        self.label_36.setFont(font7)
        self.label_36.setStyleSheet(u"color: rgb(32,123,255);\n"
"background-color:transparent;")
        self.label_37 = QLabel(self.leftFrame_2)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(31, 420, 63, 30))
        self.label_37.setFont(font7)
        self.label_37.setStyleSheet(u"color: rgb(32,123,255);\n"
"background-color:transparent;")
        self.btnDisarmedMode = QPushButton(self.page_settings)
        self.btnDisarmedMode.setObjectName(u"btnDisarmedMode")
        self.btnDisarmedMode.setGeometry(QRect(810, 30, 120, 50))
        self.btnDisarmedMode.setMinimumSize(QSize(120, 50))
        self.btnDisarmedMode.setMaximumSize(QSize(150, 16777215))
        self.btnDisarmedMode.setFont(font7)
        self.btnDisarmedMode.setStyleSheet(u"QPushButton {\n"
"border-radius: 10px;\n"
"background-color:rgba(74,16,241,255);\n"
"border: 3px solid #207bff;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(32,123,255);\n"
"}")
        self.btnGuideMode = QPushButton(self.page_settings)
        self.btnGuideMode.setObjectName(u"btnGuideMode")
        self.btnGuideMode.setGeometry(QRect(280, 30, 120, 50))
        self.btnGuideMode.setMinimumSize(QSize(120, 50))
        self.btnGuideMode.setMaximumSize(QSize(150, 16777215))
        self.btnGuideMode.setFont(font7)
        self.btnGuideMode.setStyleSheet(u"QPushButton {\n"
"border-radius: 10px;\n"
"background-color:rgba(74,16,241,255);\n"
"border: 3px solid #207bff;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(32,123,255);\n"
"}")
        self.btnAutoMode = QPushButton(self.page_settings)
        self.btnAutoMode.setObjectName(u"btnAutoMode")
        self.btnAutoMode.setGeometry(QRect(450, 30, 120, 50))
        self.btnAutoMode.setMinimumSize(QSize(120, 50))
        self.btnAutoMode.setMaximumSize(QSize(150, 16777215))
        self.btnAutoMode.setFont(font7)
        self.btnAutoMode.setStyleSheet(u"QPushButton {\n"
"border-radius: 10px;\n"
"background-color:rgba(74,16,241,255);\n"
"border: 3px solid #207bff;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(32,123,255);\n"
"}")
        self.btnQrtlMode = QPushButton(self.page_settings)
        self.btnQrtlMode.setObjectName(u"btnQrtlMode")
        self.btnQrtlMode.setGeometry(QRect(625, 30, 120, 50))
        self.btnQrtlMode.setMinimumSize(QSize(120, 50))
        self.btnQrtlMode.setMaximumSize(QSize(150, 16777215))
        self.btnQrtlMode.setFont(font7)
        self.btnQrtlMode.setStyleSheet(u"QPushButton {\n"
"border-radius: 10px;\n"
"background-color:rgba(74,16,241,255);\n"
"border: 3px solid #207bff;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(32,123,255);\n"
"}")
        self.btnMediumQuality = QPushButton(self.page_settings)
        self.btnMediumQuality.setObjectName(u"btnMediumQuality")
        self.btnMediumQuality.setGeometry(QRect(450, 120, 120, 50))
        self.btnMediumQuality.setMinimumSize(QSize(120, 50))
        self.btnMediumQuality.setMaximumSize(QSize(150, 16777215))
        self.btnMediumQuality.setFont(font7)
        self.btnMediumQuality.setStyleSheet(u"QPushButton {\n"
"border-radius: 10px;\n"
"background-color:rgba(74,16,241,255);\n"
"border: 3px solid #207bff;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(32,123,255);\n"
"}")
        self.btnLowQuality = QPushButton(self.page_settings)
        self.btnLowQuality.setObjectName(u"btnLowQuality")
        self.btnLowQuality.setGeometry(QRect(280, 120, 120, 50))
        self.btnLowQuality.setMinimumSize(QSize(120, 50))
        self.btnLowQuality.setMaximumSize(QSize(150, 16777215))
        self.btnLowQuality.setFont(font7)
        self.btnLowQuality.setStyleSheet(u"QPushButton {\n"
"border-radius: 10px;\n"
"background-color:rgba(74,16,241,255);\n"
"border: 3px solid #207bff;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(32,123,255);\n"
"}")
        self.label_38 = QLabel(self.page_settings)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(280, 210, 50, 16))
        self.label_38.setMaximumSize(QSize(50, 16777215))
        self.label_38.setFont(font5)
        self.label_38.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: \"MS Shell Dlg 2\";")
        self.idLabel = QLabel(self.page_settings)
        self.idLabel.setObjectName(u"idLabel")
        self.idLabel.setGeometry(QRect(330, 207, 100, 20))
        self.idLabel.setMinimumSize(QSize(100, 0))
        self.idLabel.setMaximumSize(QSize(50, 16777215))
        font8 = QFont()
        font8.setBold(False)
        font8.setItalic(False)
        self.idLabel.setFont(font8)
        self.idLabel.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font:\"MS Shell Dlg 2\";")
        self.historyShow = QPushButton(self.page_settings)
        self.historyShow.setObjectName(u"historyShow")
        self.historyShow.setGeometry(QRect(280, 290, 178, 60))
        self.historyShow.setMinimumSize(QSize(0, 60))
        self.historyShow.setFont(font5)
        self.historyShow.setStyleSheet(u"QPushButton {\n"
"border-radius: 10px;\n"
"background-color:rgba(74,16,241,255);\n"
"border: 3px solid #207bff;\n"
"color: #fff;\n"
"}\n"
"")
        self.historyShow.setCheckable(True)
        self.widget_22 = QWidget(self.page_settings)
        self.widget_22.setObjectName(u"widget_22")
        self.widget_22.setGeometry(QRect(270, 379, 191, 151))
        self.widget_22.setMaximumSize(QSize(999, 999))
        self.widget_22.setStyleSheet(u"border-image: url(:/icon/images/icon/poyrazLogo.ico);\n"
"background-color:transparent;")
        self.pushButton = QPushButton(self.page_settings)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(919, 440, 121, 61))
        self.pushButton.setMinimumSize(QSize(0, 0))
        self.pushButton.setMaximumSize(QSize(999, 16777215))
        self.pushButton.setFont(font7)
        self.pushButton.setStyleSheet(u"QPushButton {\n"
"border-radius: 10px;\n"
"background-color:rgba(74,16,241,255);\n"
"border: 3px solid #207bff;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgb(32,123,255);\n"
"}")
        self.gaugeWidget = QWidget(self.page_settings)
        self.gaugeWidget.setObjectName(u"gaugeWidget")
        self.gaugeWidget.setGeometry(QRect(590, 220, 221, 131))
        self.stackedWidget.addWidget(self.page_settings)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(3)
        self.connectBtn.setDefault(False)
        self.modeCheck.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Poyraz Havac\u0131l\u0131k", None))
        self.btn_poyrazLogo.setText("")
        self.btn_homePage.setText(QCoreApplication.translate("MainWindow", u"Envanter ", None))
        self.btn_package.setText(QCoreApplication.translate("MainWindow", u"Package  ", None))
        self.btn_mission.setText(QCoreApplication.translate("MainWindow", u"Mission   ", None))
        self.btn_dataFlight.setText(QCoreApplication.translate("MainWindow", u"Data F.   ", None))
        self.btn_preFlight.setText(QCoreApplication.translate("MainWindow", u"Pre F.     ", None))
        self.btn_settings.setText(QCoreApplication.translate("MainWindow", u"Settings  ", None))
        self.btn_menu.setText("")
        self.labelTitle.setText(QCoreApplication.translate("MainWindow", u"ENVANTER", None))
        self.urunpic1.setText("")
        self.urun1Sil.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.urunpic2.setText("")
        self.urun2Sil.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.urunpic3.setText("")
        self.urun3Sil.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.btn_sepeteEkle.setText(QCoreApplication.translate("MainWindow", u"Sepete Ekle", None))
        self.btn_tansiyon.setText("")
        self.btn_telefon.setText("")
        self.btn_guckaynagi.setText("")
        self.btn_tablet.setText("")
        self.btn_ilacKutusu.setText("")
        self.btn_kulaklik.setText("")
        self.btn_nebulizator.setText("")
        self.btn_boyunluk.setText("")
        self.btn_insulin.setText("")
        self.btn_kablo.setText("")
        self.btn_laptop.setText("")
        self.textisim.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u0130sim", None))
        self.textSoyad.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Soyisim", None))
        self.textTelefon.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Telefon (05**-***-**-**)", None))
        self.textGondericiGemi.setText("")
        self.textGondericiGemi.setPlaceholderText(QCoreApplication.translate("MainWindow", u"G\u00f6nderici Gemi", None))
        self.textHedefGemi.setInputMask("")
        self.textHedefGemi.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Hedef Gemi", None))
        self.labelPaketBilgisi.setText(QCoreApplication.translate("MainWindow", u"Paket Bilgisi", None))
        self.labelPaketBilgiBack.setText("")
        self.labelPaketBilgisi_2.setText(QCoreApplication.translate("MainWindow", u"Paket \u0130\u00e7eri\u011fi", None))
        self.labelPaketBilgiBack_2.setText(QCoreApplication.translate("MainWindow", u"Paket \u0130\u00e7eri\u011fi", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Paket \u0130\u00e7eri\u011fi", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Paket \u0130\u00e7eri\u011fi", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Paket \u0130\u00e7eri\u011fi", None))
        self.paketurun4.setText("")
        self.paketurun2.setText("")
        self.paketurun1.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Paket \u0130\u00e7eri\u011fi", None))
        self.paketurun3.setText("")
        self.btnOnayla.setText(QCoreApplication.translate("MainWindow", u"Onayla", None))
        self.labelPaketBilgiBack_3.setText("")
        self.labelPaketBilgisi_3.setText(QCoreApplication.translate("MainWindow", u"Rota Bilgisi", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Nereden", None))
        self.pushButton_13.setText("")
        self.labelPaketBilgiBack_4.setText("")
        self.labelPaketBilgiBack_5.setText("")
        self.textNereden_lat.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lat :", None))
        self.textNereye_lat.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lat :", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Nereye", None))
        self.textNereden_lon.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lon :", None))
        self.textNereye_lon.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lon :", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Home: ", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Target Alt: ", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Target Speed: ", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Target Speed: ", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Vehicle Mode: ", None))
        self.modeCheck_2.setItemText(0, QCoreApplication.translate("MainWindow", u"CHOOSE", None))
        self.modeCheck_2.setItemText(1, QCoreApplication.translate("MainWindow", u"GUIDE", None))
        self.modeCheck_2.setItemText(2, QCoreApplication.translate("MainWindow", u"QRTL", None))
        self.modeCheck_2.setItemText(3, QCoreApplication.translate("MainWindow", u"QLAND", None))

        self.checkCameraOn.setText(QCoreApplication.translate("MainWindow", u"CAMERA ON", None))
        self.armBtn.setText(QCoreApplication.translate("MainWindow", u"GET ARM", None))
        self.checkCameraOff.setText(QCoreApplication.translate("MainWindow", u"CAMERA OFF", None))
        self.takeOffBtn.setText(QCoreApplication.translate("MainWindow", u"TAKE OFF !!!", None))
        self.connectBtn.setText(QCoreApplication.translate("MainWindow", u"CONNECT", None))
        self.portBtn.setItemText(0, QCoreApplication.translate("MainWindow", u"9600", None))

        self.comBtn.setItemText(0, QCoreApplication.translate("MainWindow", u"COM6", None))

        self.label_location.setText("")
        self.labelSatellite.setText("")
        self.labelFixed.setText("")
        self.labelFixed_2.setText(QCoreApplication.translate("MainWindow", u"Satellite :", None))
        self.labelSatellite_2.setText(QCoreApplication.translate("MainWindow", u"Fix-Type :", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Roll", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"AirSpeed", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Alttitude", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"GroundSp", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Yaw", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Pitch", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"is Ready For Arm ?  -->", None))
        self.modeCheck.setItemText(0, QCoreApplication.translate("MainWindow", u"CHOOSE", None))
        self.modeCheck.setItemText(1, QCoreApplication.translate("MainWindow", u"GU\u0130DE", None))
        self.modeCheck.setItemText(2, QCoreApplication.translate("MainWindow", u"AUTO", None))
        self.modeCheck.setItemText(3, QCoreApplication.translate("MainWindow", u"QRTL", None))

        self.labelTelemetry.setText(QCoreApplication.translate("MainWindow", u"% 100", None))
        self.readyChech.setText(QCoreApplication.translate("MainWindow", u"Ready!!!", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"WayPoint Number -->", None))
        self.noRadioEquip.setText(QCoreApplication.translate("MainWindow", u"NO", None))
        self.gpsCheck.setText(QCoreApplication.translate("MainWindow", u"Ready", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"GPS -->", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Telemetry Signal -->", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Command Mode Check  -->", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"READY ? -->", None))
        self.yesRadioEquip.setText(QCoreApplication.translate("MainWindow", u"YES", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"SUCCESFULL !!!", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"\u0130s switch working ? -->", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Propeller and Engine  -->", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Mechanic System Check -->", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Safety fuse Check -->", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Is Camera Ready -->", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Battery Level -->", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"ESC Cable Check -->", None))
        self.escCableCheck.setText(QCoreApplication.translate("MainWindow", u"Ready", None))
        self.engineCheck.setText(QCoreApplication.translate("MainWindow", u"Ready", None))
        self.batteryLabel.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.switchCheck.setText(QCoreApplication.translate("MainWindow", u"Ready", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.safetyFuseCheck.setText(QCoreApplication.translate("MainWindow", u"Ready", None))
        self.mechanicCheck.setText(QCoreApplication.translate("MainWindow", u"Ready", None))
        self.cameraYesradio.setText(QCoreApplication.translate("MainWindow", u"YES", None))
        self.cameraNoRadio.setText(QCoreApplication.translate("MainWindow", u"NO", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"SUCCESFULL !!!", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Current Flight Mode", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Camera Quality", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"User \u0130nformation", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Flight History", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Team:", None))
        self.btnDisarmedMode.setText(QCoreApplication.translate("MainWindow", u"Disarmed", None))
        self.btnGuideMode.setText(QCoreApplication.translate("MainWindow", u"Guide", None))
        self.btnAutoMode.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.btnQrtlMode.setText(QCoreApplication.translate("MainWindow", u"QRTL", None))
        self.btnMediumQuality.setText(QCoreApplication.translate("MainWindow", u"720x1080", None))
        self.btnLowQuality.setText(QCoreApplication.translate("MainWindow", u"480x640", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"ID :", None))
        self.idLabel.setText(QCoreApplication.translate("MainWindow", u"______________", None))
        self.historyShow.setText(QCoreApplication.translate("MainWindow", u"Show", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"> Log Out", None))
    # retranslateUi

